### ISSUE TITLE
Error using transient templates

### ISSUE THREAD

**Issue by fpw** [tatuylonen/wikitextprocessor#1]
When using transient templates, I get a Python error about the "body" variable being used before it's declared. I believe in the line linked below, the index should reference "name" and not "body".

https://github.com/tatuylonen/wikitextprocessor/blob/b092f0038bb39670ecc2687f2a4d6bcc80361f40/wikitextprocessor/core.py#L1081

**Comment by tatuylonen** [comment]
Thanks!  I just merged your fix.
