### ISSUE TITLE
Set a higher `chunksize` value to decrease the process time

### ISSUE THREAD

**Issue by xxyzz** [tatuylonen/wikitextprocessor#14]
The [Python document](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.imap) says setting a large chunksize would improve speed. I tried to test this parameter on [GitHub Actions](https://github.com/xxyzz/wiktextract/actions/runs/3202850224) but all jobs exceed the 6 hours limit. I also tried to run the command on my machine but it took 10 hours to finish and I only run the command once. I'm not sure whether this parameter would make a huge difference, maybe someone with a more powerful PC could test this.

You can find my test workflow and code at here: https://github.com/xxyzz/wiktextract/actions/runs/3202850224/workflow

**Comment by xxyzz** [comment]
I found that bypass [`error()`, `warning()` and `debug()` functions](https://github.com/tatuylonen/wikitextprocessor/blob/5eb7eecd22afc7d73e52266db87010b796d5f959/wikitextprocessor/core.py#L270-L321) in the `Wtp` class would increase the performance significantly when parsing the Chinese WIktionary dump file. Maybe it's `inspect.stack()` in those functions slow down the speed.

I also found most processes are in the "uninterruptible sleep" status, the code could be faster if more processes are in the running status.

**Comment by kristian-clausal** [comment]
Testing on smaller languages, the getframeinfo stuff adds about 5% to Korean (which has a tooon of <span>-errors), and Tatu suspects this might be exacerbated when doing a lot more at once, so I think I'll basically just make the sorting system use passed strings with (hopefully) unique identifiers to use for the sorting, then add those to each error, debug and warning-call in wikitextprocessor and wiktextract; shouldn't be too hard, there was a surprisingly small number of them. That should fix that 5%.
