### ISSUE TITLE
Doesn't parse sections with italics in heading title

### ISSUE THREAD

**Issue by empiriker** [tatuylonen/wikitextprocessor#158]
The German Wiktionary can have italics in heading titles such as:

`=== {{Wortart|Substantiv|Latein}}, {{m}}, ''nachklassisch'' ===`
from page [Christus](https://de.wiktionary.org/wiki/Christus)

This currently gets parsed to 
`<ROOT(['']){} '=== ', <TEMPLATE(['Wortart'], ['Substantiv'], ['Latein']){} >, ', ', <TEMPLATE(['m']){} >, ', ', <ITALIC(){} 'nachklassisch'>, ' ==='>` 
completely missing the H3 heading, crucial for correctly parsing the page.

I have investigated the issue and believe it's caused by the use of italics in the heading. Basically, I would expect the parser to pass this test:

```python
def test_hdr_italics(self):
    tree = self.parse("test", "=== ''nachklassisch'' ===")
    print(tree) # <ROOT(['test']){} '=== ', <ITALIC(){} 'nachklassisch'>, ' ==='>
    self.assertEqual(len(tree.children), 1) # Failed
    self.assertEqual(tree.children[0].kind, NodeKind.LEVEL3)
    self.assertEqual(len(tree.children[0].largs), 1)
    self.assertEqual(tree.children[0].largs[0][0].kind, NodeKind.ITALIC)
```

However, this test fails. See comments in code example.

The issue seems to be in `token_iter()` which deals with splitting single quotes at the very beginning 

https://github.com/tatuylonen/wikitextprocessor/blob/8d80d07aa9e47c76aad7ae0b8d2def2d38570bd1/src/wikitextprocessor/parser.py#L2025-L2027

before it looks for section headings at:
https://github.com/tatuylonen/wikitextprocessor/blob/8d80d07aa9e47c76aad7ae0b8d2def2d38570bd1/src/wikitextprocessor/parser.py#L2106

I don't quite understand the reasoning for dealing with single quotes first. This is why I do not feel comfortable attempting to solve this myself.

Could someone take a look?

**Comment by xxyzz** [comment]
Geez, I haven't figure out the HTML encode error from last week and here is an even more tricky problem...

Maybe the long quote loop could be moved into the `re.finditer(token_re` loop?

**Comment by kristian-clausal** [comment]
#159 should fix this.

The issue was just oversight, this doesn't happen on en.wiktionary.org and so it never turned up.

Fix is: handle header tokenizing before partitioning on italics. This was pretty much copy-pasting bits around (thankfully), because the header tokenizing code already involved calling token_iter in the header's inner content recursively. All that was needed was to separate the header detection regex bits into its own match, see if the line is a header, then handle it as a header, otherwise do what was done previously and partition by the italics/bold tokens.

**Comment by empiriker** [comment]
Thanks a lot! This solved it indeed. 

While being only present in a low percentage of pages, this was a breaking error causing the whole section to be ignored by the extractor. Great to see that it was easily fixable!
