### ISSUE TITLE
`Can not match` Lua errors in the "ja-usex" Module

### ISSUE THREAD

**Issue by xxyzz** [tatuylonen/wikitextprocessor#170]
Some Japanese pages have this error, all of them use bold wikitext in a link. Example page: https://en.wiktionary.org/wiki/ちゃんねる, [error link](https://kaikki.org/dictionary/errors/details-Can-not-match--%E3%81%B5%E3%81%9F%E3%81%B0-%E3%81%A1%E3%82%83%E3%82%93%E3%81%AD%E3%82%8B--and--%E3%81%B5%E3%81%9F%E3%81%B0-----OnSEIP0F.html).

```
#: {{ja-usex|[[w:ja:2ちゃんねる|2'''ちゃんねる''']]|^に-'''ちゃんねる'''|{{w|2channel}}}}
```

What puzzled me is when saving the link arguments, the argument contains the bold wikitext(`'''`), but then when expanding the template, the argument now doesn't have the `'''` around "ちゃんねる". I think this is because this link is somehow parsed twice, and the wrong magic number is used to retrieve the incorrect arguments, but I don't know where and when this happened in the code.

**Comment by xxyzz** [comment]
The bold wikitexts are removed by the `clean_node_handler_fn` at https://github.com/tatuylonen/wiktextract/blob/a5720e04939a7604cddfa2addfd9b2b78c3235fe/wiktextract/page.py#L332-L338 from commit https://github.com/tatuylonen/wiktextract/commit/7d6f8438e64e3e95b5fbe82238265fb3a5fe92b5

I don't understand why this function should be used, it removes some nodes and only use their child nodes, this would change the node structure and expand to wrong text.

**Comment by xxyzz** [comment]
I guess `clean_node_handler_fn` is used for convert these nodes to plain text, but this conversion is too early. Bold and italic nodes should be converted to text after all templates are expanded.

**Comment by kristian-clausal** [comment]
Not removing the italics and bold node layers too early seems to be correct. I actually went through clean_value yesterday and noticed the italics and bold removal code there (there's a lot because it needs to use the same parsing as token parsing which is long (though not complicated)). Thumbs up from me.
