### ISSUE TITLE
Template  class="error" when expanding.

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#194]
I'm trying to extract text from french wiki dumps. Page example: https://fr.wikipedia.org/wiki/Arabie_saoudite
The page contains the following template :
```
L{{\'}}{{arabe|\'\'\'Arabie saoudite\'\'\'&lt;ref group=&quot;note&quot;&gt;Aussi plus rarement « Arabie séoudite ».&lt;/ref&gt;|العربيّة السّعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|\'\'\'royaume d\'Arabie saoudite\'\'\'|المملكة العربيّة السّعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]]. 
```

I got `<strong class="error">Template:&#x27;</strong><strong class="error">` when expanding.

**Code:** 
```python
    from wikitextprocessor import Wtp

    wikitext = """
    L{{\'}}{{arabe|\'\'\'Arabie saoudite\'\'\'|العربيّة السّعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|\'\'\'royaume d\'Arabie saoudite\'\'\'|المملكة العربيّة السّعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
    """
    wtp = Wtp()
    wtp.start_page('Test')
    wiki_data = wtp.parse(
        text=wikitext,
        expand_all=True
    )
    value = wtp.node_to_wikitext(wiki_data)
    print(value)
```

**Output**:
```L<strong class="error">Template:&#x27;</strong><strong class="error">Template:arabe</strong>, en forme longue le <strong class="error">Template:arabe</strong>, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].```

**Comment by kristian-clausal** [comment]
I am getting

```
L[[:Template:']][[:Template:arabe]], en forme longue le [[:Template:arabe]], est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
```

with the same code.

What version of wikitextprocessor are you using? The pip one will probably always be out of date, just clone the wikitextprocessor repo and use that instead.

**Comment by kristian-clausal** [comment]
Basically, to get the right output I needed to do this:

```from wikitextprocessor import Wtp
from wikitextprocessor.parser import print_tree

wikitext = """
L{{\'}}{{arabe|\'\'\'Arabie saoudite\'\'\'|العربيّة السّعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|\'\'\'royaume d\'Arabie saoudite\'\'\'|المملكة العربيّة السّعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
"""
wtp = Wtp(
    db_path="/home/kristian/Data/htmlgen/fr/fr-wikt.db",
    lang_code="fr",
    project="wikipedia",
)
wtp.start_page("Test")
wiki_data = wtp.parse(text=wikitext, expand_all=True)

print_tree(wiki_data, 2)

value = wtp.node_to_wikitext(wiki_data)
print(value)
```

It seems that if the parser can't load the template (from a database, in this case, I guess) it'll default to creating link nodes. Which is weird, I'd expect it to recreate the template with all its arguments. I'll ask Tatu about it.

**Comment by kristian-clausal** [comment]
```python
from wikitextprocessor import Wtp
from wikitextprocessor.parser import print_tree

wikitext = """
L{{\'}}{{arabe|\'\'\'Arabie saoudite\'\'\'|العربيّة السّعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|\'\'\'royaume d\'Arabie saoudite\'\'\'|المملكة العربيّة السّعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
"""
wtp = Wtp(
    db_path="/home/kristian/Data/htmlgen/fr/fr-wikt.db",
    lang_code="fr",
    project="wikipedia",
)
wtp.start_page("Test")
wiki_data = wtp.parse(text=wikitext, expand_all=False)

print_tree(wiki_data, 2)

value = wtp.node_to_wikitext(wiki_data)
print(value)
```

results in

```
L{{'}}{{arabe|'''Arabie saoudite'''|العربية السعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|'''royaume d'Arabie saoudite'''|المملكة العربية السعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
```

Which I bet is going to break if you tried to use it because it lacks all the escape characters! Or maybe not.

The issue was with "expand_all". The parser tries to, well, expand all the templates, and fails at it because it doesn't have access to the templates (through a database file in this case). The result is a link.

**Comment by xxyzz** [comment]
I think the issue author's code doesn't work is because he didn't set the correct language code. And why use `node_to_wikitext`, shouldn't we use `wtp.expand()` to get plain text? And `'` doesn't need to be escaped in `"""`.

**Comment by kristian-clausal** [comment]
There is a difference between the output I got and what the original poster got, so there's something there other than what was mentioned.

I assumed the original poster wanted the wikitext for other reasons, in which case `expand()` might not have been appropriate.

**Comment by LeMoussel** [comment]
_What version of wikitextprocessor are you using?_ 
0.4.96
Surprising because this tag does not exist in this repository. The last tag being: 0.4.95
So I installed from this repo:  ` pip install git+https://github.com/tatuylonen/wikitextprocessor.git`
```shell
Successfully installed lupa-2.1 lxml-5.1.0 mediawiki-langcodes-0.1.2 psutil-5.9.8 wikitextprocessor-0.4.96
```
and with the use `wtp.expand()`, I got this :
```
L[[:Modèle:']][[:Modèle:arabe]], en forme longue le [[:Modèle:arabe]], est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
```
Which does not exactly give the result displayed on the Wikpedia page: [Arabie saoudite](https://fr.wikipedia.org/wiki/Arabie_saoudite)
The result should be something like this?
`L'Arabie saoudite, en forme longue le royaume d'Arabie saoudite, est une monarchie absolue islamique dirigée par la dynastie des Saoud, ...`

**Python code:**
```python
    from wikitextprocessor import Wtp
    from wikitextprocessor.parser import print_tree

    wikitext = """
    L{{\'}}{{arabe|\'\'\'Arabie saoudite\'\'\'|العربيّة السّعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|\'\'\'royaume d\'Arabie saoudite\'\'\'|المملكة العربيّة السّعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
    """
    wtp = Wtp(
        db_path="fr-wikt.db",
        lang_code="fr",
        project="wikipedia",
    )
    wtp.start_page("Test")
    text = wtp.expand(text=wikitext)
    print(text)
 ```

**Comment by kristian-clausal** [comment]
Just to make sure, have you created fr-wikt.db? This is the big database file created by wiktwords when you run it on the database dump file from Wiktionary. If you haven't, then the expansion can't work because it doesn't have access to the templates, there is no "Template:arabe" page that it can expand into full text.

**Comment by kristian-clausal** [comment]
It's a long process, unfortunately, especially on a home machine.

Honestly, I wonder if we should have downloads to the .db database files we create... I'll ask Tatu.

To create the .db file all you need is to the run wiktwords with the --db-path parameter for the .db file's path and name on the appropriate wiktionary dump file.

`lang=fr; wget https://dumps.wikimedia.org/${lang}wiktionary/latest/${lang}wiktionary-latest-pages-articles.xml.bz2` to download the appropriate file in linux, this was easier to copypaste than hunting down the link (lol).

then run `wiktwords --db-path="fr-wikt.db" --dump-file-language-code "fr" frwiktionary-latest-pages-articles.xml.bz2`... I think that's the minimum needed.

Technically you dont' *need* the database-file... If you want to extract every page out of the dump.xml.bz2 file each time. The database file acts as a cache that saves all the pages from the dump so that you can do everything as quickly as possible, so creating the database file is basically mandatory anyhow.

**Comment by LeMoussel** [comment]
To run `wiktwords`, I have to install [wiktextract](https://github.com/tatuylonen/wiktextract) via `pip install wiktextract`
Is it correct ?

**Comment by kristian-clausal** [comment]
We were previously missing a parameter for wiktwords that would allow the creation of a .db without doing the extraction process. Use `--skip-extraction` when creating the db-file to do just that, should speed up things considerably.

**Comment by LeMoussel** [comment]
Hummm... Got this with `--skip-extraction`
```shell

(.venv) dev@dev-B550M-DS3H:~/Python/WikiExtractor/wiktextract$ wiktwords --db-path="fr-wikt.db" --dump-file-language-code "fr" --skip-extraction ../frwiktionary-latest-pages-articles.xml.bz2usage: wiktwords [-h] [--out OUT] [--errors ERRORS] [--dump-file-language-code DUMP_FILE_LANGUAGE_CODE] [--language-code LANGUAGE_CODE] [--language-name LANGUAGE_NAME] [--all-languages]
                 [--pages-dir PAGES_DIR] [--all] [--translations] [--pronunciations] [--linkages] [--compounds] [--redirects] [--examples] [--etymologies] [--inflections] [--descendants]
                 [--page PAGE] [--db-path DB_PATH] [--num-processes NUM_PROCESSES] [--verbose] [--human-readable] [--override OVERRIDE] [--use-thesaurus] [--profile]
                 [--categories-file CATEGORIES_FILE] [--modules-file MODULES_FILE] [--templates-file TEMPLATES_FILE] [--redirects-file REDIRECTS_FILE]
                 [--inflection-tables-file INFLECTION_TABLES_FILE] [--debug-cell-text DEBUG_CELL_TEXT] [--quiet] [--search-pattern SEARCH_PATTERN]
                 [path]
wiktwords: error: unrecognized arguments: --skip-extraction
(.venv) dev@dev-B550M-DS3H:~/Python/WikiExtractor/wiktextract$
``` 

I do this for installation :
```shell
git clone https://github.com/tatuylonen/wiktextract.git
cd wiktextract
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install -U pip
python3 -m pip install --use-pep517 .
```

**Comment by kristian-clausal** [comment]
Yeah, I just merged it twenty minutes ago (should have specified lol); pull the repo again and reinstall should do the trick.

**Comment by LeMoussel** [comment]
OK but I installed with `python3 -m pip install --use-pep517 .`
`python3 -m pip install -e --use-pep517 .` produce an error.

Let's go !
`wiktwords --db-path="fr-wikt.db" --dump-file-language-code "fr" --skip-extraction ../frwiktionary-latest-pages-articles.xml.bz2`

```
2024-02-05 13:23:09,096 INFO: Capturing words for: fr, mul
2024-02-05 13:23:09,130 INFO: First phase - extracting templates, macros, and pages
2024-02-05 13:23:09,130 INFO: skip_extract_dump: False, save_pages_path: None
2024-02-05 13:23:09,130 INFO: dump file path: ../frwiktionary-latest-pages-articles.xml.bz2
2024-02-05 13:23:11,004 INFO:   ... 10000 raw pages collected
2024-02-05 13:23:12,031 INFO:   ... 20000 raw pages collected
2024-02-05 13:23:12,986 INFO:   ... 30000 raw pages collected
2024-02-05 13:23:13,806 INFO:   ... 40000 raw pages collected
2024-02-05 13:23:14,596 INFO:   ... 50000 raw pages collected
2024-02-05 13:23:15,286 INFO:   ... 60000 raw pages collected
2024-02-05 13:23:15,981 INFO:   ... 70000 raw pages collected
2024-02-05 13:23:16,693 INFO:   ... 80000 raw pages collected
2024-02-05 13:23:17,384 INFO:   ... 90000 raw pages collected
.....
```

**Comment by LeMoussel** [comment]
Now with the use of the DB created `fr-wikt.db`, I have this result:
```
L’<bdi  dir="rtl" class="script-Arab" style="font-family:'Noto Sans Arabic UI','Noto Sans Arabic',Andalus,'Noto Naskh Arabic UI','Noto Naskh Arabic','Traditional Arabic',Amiri,'Noto Kufi Arabic','Microsoft Uighur','Tahoma','DejaVu Sans',sans-serif;font-size-adjust:70%;">'''Arabie saoudite'''</bdi>, en forme longue le <bdi  dir="rtl" class="script-Arab" style="font-family:'Noto Sans Arabic UI','Noto Sans Arabic',Andalus,'Noto Naskh Arabic UI','Noto Naskh Arabic','Traditional Arabic',Amiri,'Noto Kufi Arabic','Microsoft Uighur','Tahoma','DejaVu Sans',sans-serif;font-size-adjust:70%;">'''royaume d'Arabie saoudite'''</bdi>, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
```

Python code:
```python
    from wikitextprocessor import Wtp

    wikitext = """
    L{{\'}}{{arabe|\'\'\'Arabie saoudite\'\'\'|العربيّة السّعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|\'\'\'royaume d\'Arabie saoudite\'\'\'|المملكة العربيّة السّعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
    """
    wtp = Wtp(
        db_path="fr-wikt.db",
        lang_code="fr",
        project="wikipedia",
    )
    wtp.start_page("Test")
    text = wtp.expand(text=wikitext)
    print(text)
```

**Comment by kristian-clausal** [comment]
That is the correct output, but if you want it cleaned up there are cleaning functions for that; I am away from the code until tomorrow, hopefully you can survive on your own till then.On Feb 5, 2024 15:14, LeMoussel ***@***.***> wrote:
Now with the use of the DB created fr-wikt.db, I have this result:
L’<bdi  dir="rtl" class="script-Arab" style="font-family:'Noto Sans Arabic UI','Noto Sans Arabic',Andalus,'Noto Naskh Arabic UI','Noto Naskh Arabic','Traditional Arabic',Amiri,'Noto Kufi Arabic','Microsoft Uighur','Tahoma','DejaVu Sans',sans-serif;font-size-adjust:70%;">'''Arabie saoudite'''</bdi>, en forme longue le <bdi  dir="rtl" class="script-Arab" style="font-family:'Noto Sans Arabic UI','Noto Sans Arabic',Andalus,'Noto Naskh Arabic UI','Noto Naskh Arabic','Traditional Arabic',Amiri,'Noto Kufi Arabic','Microsoft Uighur','Tahoma','DejaVu Sans',sans-serif;font-size-adjust:70%;">'''royaume d'Arabie saoudite'''</bdi>, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].

Python code:
    from wikitextprocessor import Wtp

    wikitext = """
    L{{\'}}{{arabe|\'\'\'Arabie saoudite\'\'\'|العربيّة السّعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|\'\'\'royaume d\'Arabie saoudite\'\'\'|المملكة العربيّة السّعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
    """
    wtp = Wtp(
        db_path="fr-wikt.db",
        lang_code="fr",
        project="wikipedia",
    )
    wtp.start_page("Test")
    text = wtp.expand(text=wikitext)
    print(text)

**Comment by LeMoussel** [comment]
Yep ! I will survive alone until then :)
Thank you very much for your help.

**Comment by xxyzz** [comment]
You don't need the `wiktwords` command from the wiktextract project to create a SQLite db file, the db file can be created by using the [process_dump](https://github.com/tatuylonen/wikitextprocessor/blob/762e3e622abe3fa34b62df454e2ce3eae8f03509/src/wikitextprocessor/dumpparser.py#L91) function. This function runs in a single process so it can run at any home pc.

[`clean_code`](https://github.com/tatuylonen/wiktextract/blob/fd7bc18deaee791ae5b4058eced01c87db178a4f/src/wiktextract/page.py#L322) could be used to convert wikitext and HTML tags to plain text.

**Comment by xxyzz** [comment]
And you use the wrong dump file, you should use the French Wikipedia dump file not French Wiktionary dump file. Their template pages are different.

**Comment by kristian-clausal** [comment]
That was my fault, completely forgot this was for Wikipedia.

**Comment by LeMoussel** [comment]
OK To summarize

- Download French Wikipedia dump file: `frwiki-latest-pages-articles.xml.bz2`
- Create SQLite db file, by using the [process_dump](https://github.com/tatuylonen/wikitextprocessor/blob/762e3e622abe3fa34b62df454e2ce3eae8f03509/src/wikitextprocessor/dumpparser.py#L91) function.
- use `clean_node()` to convert wikitext and HTML tags to plain text.

For process_dump, I need to do this:
```python
from functools import partial
from typing import Any

from wikitextprocessor.dumpparser import process_dump
from wikitextprocessor import Wtp

def page_handler(wtp: Wtp, page: Page) -> Any:
	pass
	
wtp = Wtp(
    db_path="fr-wiki-latest.db",
    lang_code="fr",
    project="wikipedia",
)

process_dump(
    wtp,
    "frwiki-latest-pages-articles.xml.bz2"
)

for _ in map(partial(page_handler, wtp), wtp.get_all_pages([0])):
    pass

```` 

I couldn't find any documentation on  `clean_node()` . Should we proceed in this way?
```python
from wiktextract.wxr_context import WiktextractContext
from wiktextract.config import WiktionaryConfig
from wikitextprocessor import Wtp

wikitext = """
L{{\'}}{{arabe|\'\'\'Arabie saoudite\'\'\'|العربيّة السّعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|\'\'\'royaume d\'Arabie saoudite\'\'\'|المملكة العربيّة السّعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
"""

wtp = Wtp(
    db_path="fr-wiki-latest.db",
    lang_code="fr",
    project="wikipedia",
)
wxr = WiktextractContext(wtp, WiktionaryConfig())
wxr.wtp.start_page("Test")
tree_node = wxr.wtp.parse(text=wikitext, expand_all=True)
clean_node(wxr, tree_node)
````

**Comment by kristian-clausal** [comment]
clean_node returns a string that you need to print, but afaict fine. Creating the db-file with wiktextract is probably simpler if that doesn't work out.

**Comment by LeMoussel** [comment]
I don't understand what you mean by _Creating the db-file with wiktextract is probably simpler if that doesn't work out._

**Comment by kristian-clausal** [comment]
It is probably simpler to create the database file with wiktwords* I meant to say. Wiktwords is the command bundled with wiktextract, so I was talking about the things mentioned earlier in this thread. Scripting everything with scratch with just wikitextprocessor seems excessive.

**Comment by LeMoussel** [comment]
OK, so I'm going to run this
`wiktwords --db-path="fr-wiki-latest.db" --dump-file-language-code "fr" --skip-extraction ../frwiki-latest-pages-articles.xml.bz2`

**Comment by LeMoussel** [comment]
OK, SQLite database: `fr-wiki-latest.db` created ⇒ 20.9 GB
I'm going to take the tests again

**Comment by LeMoussel** [comment]
I'm on the right track... :)

```python
    from wikitextprocessor import Wtp
    from wiktextract.wxr_context import WiktextractContext
    from wiktextract.config import WiktionaryConfig
    from wiktextract.page import clean_node

    wtp = Wtp(
        db_path="fr-wiki-latest.db",
        lang_code="fr",
        project="wikipedia",
    )

    wikitext = """
    L{{\'}}{{arabe|\'\'\'Arabie saoudite\'\'\'|العربيّة السّعودية|al-ʿarabiyya as-saʿūdiyya}}, en forme longue le {{arabe|\'\'\'royaume d\'Arabie saoudite\'\'\'|المملكة العربيّة السّعودية|al-mamlaka al-ʿarabiyya as-saʿūdiyya}}, est une [[Absolutisme|monarchie absolue]] [[État islamique|islamique]] dirigée par la [[dynastie saoudienne|dynastie des Saoud]], depuis sa création en 1932 par [[Abdelaziz ibn Saoud]].
    """
    wxr = WiktextractContext(wtp, WiktionaryConfig())
    wxr.wtp.start_page("ExtractText")
    tree_node = wxr.wtp.parse(text=wikitext, expand_all=True)
    sense_data = {}
    text = clean_node(
        wxr=wxr,
        sense_data=None,
        wikinode=tree_node
    )
   print(text)
``` 
Product this output
```
2024-02-09 13:58:07 INFO     Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-02-09 13:58:07 INFO     NumExpr defaulting to 8 threads.
ExtractText: ERROR: LUA error in #invoke('Langue', 'langue') parent ('Modèle:Langue', {1: 'ar', 2: 'العربيّة السّعودية'}) at ['ExtractText', 'arabe', '#if', '#if', 'Arabe/Arabe', 'Langue', '#invoke']
	Loading module failed in #invoke: Langue
[string "Module:Langue/Data"]:1644: bad argument #1 to 'lower' (string expected, got nil)
ExtractText: ERROR: LUA error in #invoke('Langue', 'langue') parent ('Modèle:Langue', {1: 'ar-Latn-alalc97', 2: 'al-ʿarabiyya as-saʿūdiyya'}) at ['ExtractText', 'arabe', '#if', '#if', 'Arabe/ALA-LC', 'Langue', '#invoke']
	Loading module failed in #invoke: Langue
[string "Module:Langue/Data"]:1644: bad argument #1 to 'lower' (string expected, got nil)
ExtractText: ERROR: LUA error in #invoke('Langue', 'langue') parent ('Modèle:Langue', {1: 'ar', 2: 'المملكة العربيّة السّعودية'}) at ['ExtractText', 'arabe', '#if', '#if', 'Arabe/Arabe', 'Langue', '#invoke']
	Loading module failed in #invoke: Langue
[string "Module:Langue/Data"]:1644: bad argument #1 to 'lower' (string expected, got nil)
ExtractText: ERROR: LUA error in #invoke('Langue', 'langue') parent ('Modèle:Langue', {1: 'ar-Latn-alalc97', 2: 'al-mamlaka al-ʿarabiyya as-saʿūdiyya'}) at ['ExtractText', 'arabe', '#if', '#if', 'Arabe/ALA-LC', 'Langue', '#invoke']
	Loading module failed in #invoke: Langue
[string "Module:Langue/Data"]:1644: bad argument #1 to 'lower' (string expected, got nil)
ExtractText: DEBUG: unmatched <nowiki> at ['ExtractText'] parsing ExtractText
ExtractText: DEBUG: no corresponding start tag found for </nowiki> at ['ExtractText'] parsing ExtractText
ExtractText: DEBUG: unmatched <nowiki> at ['ExtractText'] parsing ExtractText
ExtractText: DEBUG: no corresponding start tag found for </nowiki> at ['ExtractText'] parsing ExtractText

L'Arabie saoudite (en arabe : , ), en forme longue le royaume d'Arabie saoudite (en arabe : , ), est une monarchie absolue islamique dirigée par la dynastie des Saoud, depuis sa création en 1932 par Abdelaziz ibn Saoud.
``` 

Any idea why I have ` LUA error in #invoke('Langue', 'langue')`?
Because of this error, is this why there `(en arabe : , )`

**Comment by kristian-clausal** [comment]
You are correct that the debug stuff should probably be in standard error or disableable. We're just so used to outputting the data into json-files and using standard output as a logging system... We'll look into it.

===

There seems to be some issue, maybe with our implementation of mw.languages.fetchLanguageNames... 

https://fr.wikipedia.org/w/index.php?title=Module:Langue/Data&action=edit
```lua
for k, v in pairs( mwLangFr ) do
	if not p[ k ] then
		p[ k ] = { code = k, nom = v }
		table.insert( p.langueMediaWikiManquantes, k )
	end

	-- mwLangOriginal et mwLangFr ont les mêmes keys, du coup on peut traiter les deux dans cette itération

	local nomOriginal = ustringLower( mwLangOriginal[ k ] )
	if not p[ nomOriginal ] then
		p[ nomOriginal ] = p[ k ]
	end

	local nomFr = ustringLower( v )
	if not p[ nomFr ] then
		p[ nomFr ] = p[ k ]
	end
end
```
mwLangFr and mwLangOriginal should have the same keys, but mwLangOriginal is returning nil (they key is missing).
```lua
local mwLangOriginal = mw.language.fetchLanguageNames()
local mwLangFr = mw.language.fetchLanguageNames( 'fr' )
```

fetchLanguageNames is our own implementation, and afaict there's nothing wrong with it. The first one returns a dict/table of language codes mapped to their original language names, the second one a table with language codes mapped to their French names... If we're iterating over mwLangFr, then it would follow that there are keys in mwLangFr present missing from mwOriginalLang, and indeed, it seems that this is true both ways.

Yeah, the issue seems to be that in our implementation, mwLangFr and mwLangOriginal do NOT 'ont les mêmes keys', which breaks when lower() receives a nil value.

I tried to just do a naive change to our fetchLanguageNames implementation, but it didn't work: I thought that if I got the language codes from what is effectively mwLangOriginal and added it to mwLangTargetedLanguage (mwLangFr) it would work out, but I forgot that I'd already noticed that mwLangOriginal was *also* missing stuff from mwLangFr.

The implementation relies on xxyzz's mediawiki_languagecodes that uses a baked-in sqlite database to query for these things, and the table construction is a bit too intermediate level for me to touch (at a beginner SQL level), so I'll leave this to @xxyzz, next week.

TODO:

- [ ] **mediawiki_languagecodes.get_all_names** should return *all possible language codes as keys*, even if they would have an empty string value?

**Comment by kristian-clausal** [comment]
xxyzz's update to mediawiki_langcodes and to wikitextprocessor has fixed the issue with Lang. You need to update mediawiki_langcodes to 0.20 (`python -m pip install -U mediawiki_langcodes`) and pull wikitextprocessor again.

**Comment by LeMoussel** [comment]
What do you mean by `pull wikitextprocessor again.`?
(Excuse me, I'm newbie with Git)

**Comment by kristian-clausal** [comment]
If you're git cloned wikitextprocessor locally (which you have, I'm pretty sure, otherwise none of this would work... I think), and you've installed it with `pip install -e [...]` (where the ... is just the other stuff), you can 'update' wikitextprocessor by using the command `git pull` anywhere in the wikitextprocessor git folder. It will download everything that's been 'pushed' to the repo here. If you didn't install with `pip install -e`, then you also need to reinstall it using pip install again (and you could at this point switch to installing the editable version by just using the `-e` flag).

**Comment by LeMoussel** [comment]
It's OK. 
```bash
dev@dev-B550M-DS3H:~/Python/WikiExtractor$ cd wikitextprocessor
dev@dev-B550M-DS3H:~/Python/WikiExtractor/wikitextprocessor$ git pull
Updating fdd30e1..6a7890c
Fast-forward
 README.md                        |  2 ++
 pyproject.toml                   |  2 ++
 src/wikitextprocessor/common.py  | 30 ++++++++++++++++++++++++++++++
 src/wikitextprocessor/core.py    | 30 +++++++++++++++++++++++++++---
 src/wikitextprocessor/luaexec.py |  2 +-
 src/wikitextprocessor/parser.py  | 37 -------------------------------------
 tests/test_parser.py             | 93 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 7 files changed, 155 insertions(+), 41 deletions(-)
```
And do
```bash
python3 -m pip install -U mediawiki_langcodes
```

**Comment by LeMoussel** [comment]
Well done !
With the correction of @xxyzz on `mediawiki_langcodes` and you on `wikitextprocessor`, there are no more errors.
