### ISSUE TITLE
Template `{{date-|....}}` is misinterpreted?

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#199]
Under the same conditions as #198,  It seems that template `{{date-|....}}` is misinterpreted.

**For example:** 
`Le {{date-|6 décembre 2015}}, `  given `Le <>6 décembre 2015,`

The `<>` should not be present.
The result should be:  `Le 6 décembre 2015,`

**Comment by kristian-clausal** [comment]
I am pretty sure the `<>` is from a `<time>` element, generated by a module Module:Date called by Template:date-, with the `</>` getting lost at the end of the string (but it appears if you put something after that...)...

Aaaaagh. But why?

**Comment by kristian-clausal** [comment]
I've been looking deeper into this, and the offending `<>... </>` pairs aren't actually from the `<time>` tags; when we run the lua code invoker on the Date module, the output is `invoke_fn: invoke_args=('Date', 'modeleDate', 'nolinks=1') parent=('Modèle:Date-', {1: '6 décembre 2015'}) LUA ret='<><time class="nowrap" data-sort-value="2015-12-06" datetime="2015-12-06">6 décembre 2015</time></>'`, with the empty tags appearing.

**Comment by LeMoussel** [comment]
Would it be possible to explain to me how to run the Lua code invoker?
For example on the Date module.

**Comment by kristian-clausal** [comment]
You can just use Wikitextprocessor Wtp.expand(), or if you want to go deeper there's call_lua_sandbox in wikitextprocessor.luaexec

I think I found the culprit:

```lua
	-- On ajoute un peu de sémantique.
	local wikiHtml = mw.html.create( '' )  -- HERE

	if julienDate then
		wikiHtml:tag( 'span')
				:addClass( 'nowrap' )
				:attr( 'data-sort-value', isoTexte )
				:wikitext( julienDate )
				:node( julienSup )
				:done()
			:wikitext( julienSep )
	end
...
```

This is from Module:Date/_modeleDate, a helper function for modeledate. mw.html.create creates an HTML object, and then the later code (continuing from that snippet, too) creates more elements and other stuff using methods, but the first object is created with the `''`-tag. I'm 99% sure that's the culprit, for some reason our implementation actually renders the empty tags, or doesn't remove it at some point.

**Comment by kristian-clausal** [comment]
Yeah, our implementation didn't check if a tagname was an empty string, thus outputting `<>` and `</>`. I fixed it and tests pass, but I'll write a couple of tests, which should take a bit longer.

**Comment by kristian-clausal** [comment]
> Would it be possible to explain to me how to run the Lua code invoker? For example on the Date module.

Actually, for testing the simplest way might actually be to use the unittests.

For example, to test the changes in mw.html I just made, I copied and pasted a test in tests/test_lua.py:

```python
    def test_mw_html(self):
        self.wtp.add_page(
            "Module:test",
            828,
            body="""
            local export = {}
            function export.test()
                local wikiHtml = mw.html.create( '' )
                wikiHtml:tag('span')
                        :wikitext('foo')
                        :done()
                return tostring(wikiHtml)
            end
            return export
            """,
            model="Scribunto",
        )
        self.wtp.start_page("")
        self.assertEqual(
            # Should not result in "<><span>foo</span>" or
            # <><span>foo</span></> due to the empty string in `create('')`
            self.wtp.expand("{{#invoke:test|test}}"),
            "<span>foo</span>",
        )
```

You create a module page with Wtp.add_page() containing the lua code, start a new page to be 'processed' with Wtp.star_page, then use Wtp.expand to expand a template with `#invoke:test|test` (I got an error without the extra parameter, apparently that's a thing). Currently, tests can be run with `python -m unittest tests/test_lua.py` for example, gotta see if I can figure out the syntax for running a single test function after this...

**Comment by LeMoussel** [comment]
Thank you so much

**Comment by LeMoussel** [comment]
For exemple:
```python
from unittest import TestCase

class TestLua(TestCase):
    def setUp(self):
        from wikitextprocessor import Wtp

        self.wtp = Wtp(
            lang_code="fr",
            project="wikipedia",
        )

    def tearDown(self):
        self.wtp.close_db_conn()

    def test_lua_env(self):
        self.wtp.add_page(
            "Module:test-lua",
            828,
            """
            local export = {}

            function export.func_test()
                return "OK Test LUA"
            end

            return export
            """,
            model="Scribunto",
        )

        self.wtp.start_page("Test LUA")
        self.assertEqual(
            self.wtp.expand("{{#invoke:test-lua|func_test}}"),
            "OK Test LUA"
        )

```

**Comment by LeMoussel** [comment]
It's OK. Below the test.
**Note**: If you update the package via [wiktextract](https://github.com/tatuylonen/wiktextract?tab=readme-ov-file#install-from-source), this does not install the latest version of `wikitextprocessor`.
You need to update via [wikitextprocessor](https://github.com/tatuylonen/wikitextprocessor/?tab=readme-ov-file#installing)

```python
from unittest import TestCase

from wikitextprocessor import Wtp
from wiktextract.page import clean_node
from wiktextract.wxr_context import WiktextractContext
from wiktextract.config import WiktionaryConfig


class TestDate(TestCase):
    def setUp(self):

        self.wxr = WiktextractContext(
            wtp = Wtp(
                db_path="fr-wiki-latest.db",
                lang_code="fr",
                project="wikipedia",
            ),
            config=WiktionaryConfig()
        )


    def tearDown(self):
        self.wxr.wtp.close_db_conn()

    def test_date(self):
        self.wxr.wtp.start_page("Test Date")
        tree = self.wxr.wtp.parse(text="Le {{date-|14 février 2024}}", expand_all=True)
        text = clean_node(
            wxr=self.wxr,
            sense_data={},
            wikinode=tree,
        )
        self.assertEqual(text, 'Le 14 février 2024')
```

**Comment by kristian-clausal** [comment]
Yeah, that's a stumbling-block. Should add some documentation to that effect, that if you're installing from source you need to keep both packages updated separately.
