### ISSUE TITLE
Module not found because of inconsistent naming in lua modules

### ISSUE THREAD

**Issue by Wyrun** [tatuylonen/wikitextprocessor#20]
This lua module requires "Module:language/data" https://uk.wiktionary.org/wiki/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C:language
But I get "module not found" error because there is no such module on uk.wiktionary, but "Модуль:language/data"

Which is saved as "Модуль:language/data" and thus cannot be found in mw.loadData("Module:languages/data")

The simplest solution would be to use .replace("Module:", "Модуль:") or other namespace name for other languages.
Same goes for "Template". Already tried and it seems to fix most of the errors.

It should be replaced inside Lua Modules code or just everywhere while parsing the dump

Maybe in read_by_title(): rawdata.decode("utf-8").replace(...)
Or maybe in dumpparser.py raplace_namespaces_to_local_namespaces(....decode("utf-8"))
Or maybe in Lua Modules code before executing them.

**Comment by kristian-clausal** [comment]
@xxyzz how do you handle this problem with zh.wiktionary?

**Comment by Wyrun** [comment]
It did work with Ukrainian by just writing a replace function in dumpparser.py:
   to replace any text after being decoded .decode("utf-8") to whatever was in the appropriate namespaces.json file.
Also in _sandbox_phase2.lua:
   if a module not found in _new_loader(mod_name)
   trying to look for it with _new_loader(module_ns_name .. ":" .. mod_name)
I got rid of most "lua error" and "lua debug" messeges
I really need to parse many wiktionary dumps for my language-learning-app so I'm going for the simplest solution locally.
I'll see if it works well for other languages too, if so, I will try to upload the changes to the code.

**Comment by Wyrun** [comment]
I don't know, this error isn't probably because of hardcoded namespaces, it occurred because in the Lua Modules from wiktionary mw.loadData("Module:languages/data") was written, when the language used is Ukrainan and if you try to go to uk.wiktionary.org/wiki/Module:languages/data it redirects to uk.wiktionary.org/wiki/Модуль:languages/

But when executing a lua module the error "module not found happened", because such a redirect is probably not coded there?

**Comment by xxyzz** [comment]
I don't know how you use the code but this patch probably would fix the error:

```diff
diff --git a/wikitextprocessor/luaexec.py b/wikitextprocessor/luaexec.py
index 3940b6b..159bd13 100644
--- a/wikitextprocessor/luaexec.py
+++ b/wikitextprocessor/luaexec.py
@@ -91,23 +91,30 @@ def lua_loader(ctx, modname):
     assert isinstance(modname, str)
     modname = modname.strip()
     local_module_ns_name = ctx.NAMESPACE_DATA["Module"]["name"]
-    if modname.startswith(local_module_ns_name + ":"):
+
+    # Local name usually not used in Lua code
+    if modname.startswith(("Module:", local_module_ns_name + ":")):
         # Canonicalize the name
         modname = ctx._canonicalize_template_name(modname)
 
         # First try to load it as a module
-        if modname.startswith(local_module_ns_name + ":_"):
+        if modname.startswith(("Module:_", local_module_ns_name + ":_")):
             # Module names starting with _ are considered internal and cannot be
             # loaded from the dump file for security reasons.  This is to ensure
             # that the sandbox always gets loaded from a local file.
             data = None
         else:
             data = ctx.read_by_title(modname)
-            # Chinese Wikipedia capitalizes the first letter of module name
-            # can't use str.capitalize(), it'll cause error for "Module:Cmn-pron-Sichuan"
             if data is None:
                 module_name_len = len(local_module_ns_name)
-                data = ctx.read_by_title(local_module_ns_name + ":" + modname[module_name_len + 1].upper() + modname[module_name_len + 2:])
+                new_module_title = local_module_ns_name + ":"
+                # Chinese Wikipedia capitalizes the first letter of module name
+                # can't use str.capitalize(), it'll cause error for "Module:Cmn-pron-Sichuan"
+                if ctx.lang_code == "zh":
+                    new_module_title += modname[module_name_len + 1].upper() + modname[module_name_len + 2:]
+                else:
+                    new_module_title += modname[module_name_len + 1:]
+                data = ctx.read_by_title(new_module_title)
     else:
         # Try to load it from a file
         path = modname

```

**Comment by Wyrun** [comment]
Yes, that did fix the errors addressed.
Thank you very much.
