### ISSUE TITLE
Avoiding magic numbers for Wiki namespace ids

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wikitextprocessor#204]
It would be ideal to move all magic number Wiki namespace ids to constants. I still don't really know what they do and what their purpose really is.

**Comment by xxyzz** [comment]
I guess you mean some namespace ids in the tests that are used to add pages? I think that's the only place namespace id numbers are used directly. Mostly the main(0), template(10) and module(828) namespace ids are used.

Only a few namespace ids are shared among different wiki projects, we can't use constants.

In tests we could use `wtp.NAMESPACE_DATA["Template"]["id"]` to replace the id number 10.

**Comment by kristian-clausal** [comment]
I guess the tests must have made me think there were more of these around.
