### ISSUE TITLE
Strip newline character at the end of unnamed template arguments

### ISSUE THREAD

**Issue by xxyzz** [tatuylonen/wikitextprocessor#208]
Error page: https://ru.wiktionary.org/wiki/adygejski
Error message: https://kaikki.org/ruwiktionary/errors/details-No-declension-pattern-matches--adygejs-jTm2fWw4.html

Wikitext:

```
{{прил pl
|слоги={{по-слогам|a|dy|gej|ski}}|adygejski
}}
```

Lua error:

```
[adygejski (Польский морфологические и синтаксические свойства)](https://kaikki.org/ruwiktionary/All%20languages%20combined/meaning/a/ad/adygejski.html) LUA error in #invoke('inflection adj pl', 'template_decl_auto', 'adygejski\n') parent ('Шаблон:прил pl', {'слоги': 'a<span class="hyph" style="color:lightgreen;">-</span>dy<span class="hyph" style="color:lightgreen;">-</span>gej<span class="hyph" style="color:lightgreen;">-</span>ski', 1: 'adygejski\n'})

[string "inflection adj pl"]:310: No declension pattern matches 'adygejski
'
```

White space characters around unnamed template argument are not removed except the newline character at the end. In this case, "adygejski" should be passed to template ["прил pl"](https://ru.wiktionary.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:%D0%BF%D1%80%D0%B8%D0%BB_pl) and "inflection_adj_pl"  lua module not "adygejski\n".

**Comment by kristian-clausal** [comment]
Could you unpack; should the white space be removed or not be removed?

**Comment by xxyzz** [comment]
Only the "\n" at the end should be removed. I tried to fix this but then found I only removed the newline for templates not the arguments used in Lua module(`frame.args` and `frame:getParent().args`). I not sure where this strip newline code should be added to.

**Comment by kristian-clausal** [comment]
```python
r_split(v: str) -> list[str]:
            args = list(
                # m.group(1).removesuffix("\n")
                m.group(1)
                for m in re.finditer(
                    # re.X = ignore whitespace and comments, re.I = ignore case
                    r"""(?xi)\|(
                            (
                                <([-a-zA-Z0-9]+)\b[^>]*(?<!/)>  # html start tag
                                    [^][{}]*?  # element contents
                                               # (including `|`'s)
                                    </\3\s*>   # end tag
                            |   [^|]           # everything else
                            )*
                          )""",
                    "|" + v,  # first/only argument needs a vbar
                )
            )
            return args
```

It could work here, but it breaks a lot of tests and some functionality; if we 'revert' the parse-tree, we might want to keep the transformation as symmetrical as possible, and this is a destructive process. I'll try to figure out if we can .removesuffix("\n") as some other point.
