### ISSUE TITLE
EVOL: Store ID Page in SQLite database file.

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#218]
It would be nice to have the Wikipedia page ID stored in the SQLite database file.
If I understood correctly, following this [XML schema](https://www.mediawiki.org/xml/export-0.10.xsd), this would correspond to this field: 
```xml
<!-- optional page ID number -->
<element name="id" type="positiveInteger"/>
```

**Comment by xxyzz** [comment]
Is this data used somewhere to convert page text?

**Comment by LeMoussel** [comment]
Maybe I can have this information via Wikipedia API or WikiData API?
What do you think?
