### ISSUE TITLE
WARNing "unrecognized time syntax in #time ..."

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#219]
On Wikipedia [Apple](https://fr.wikipedia.org/wiki/Apple) page, theres is Warning message on
_[Apple va devoir payer une grosse amende pour avoir violé un brevet](http://www.challenges.fr/telecoms/20151017.CHA0608/apple-va-devoir-payer-une-grosse-amende-pour-avoir-viole-un-brevet.html) [[archive](https://archive.wikiwix.com/cache/?url=http%3A%2F%2Fwww.challenges.fr%2Ftelecoms%2F20151017.CHA0608%2Fapple-va-devoir-payer-une-grosse-amende-pour-avoir-viole-un-brevet.html)] [« Copie archivée »](https://web.archive.org/web/20180722200606/http://www.challenges.fr/telecoms/20151017.CHA0608/apple-va-devoir-payer-une-grosse-amende-pour-avoir-viole-un-brevet.html) (version du 22 juillet 2018 sur [Internet Archive](https://fr.wikipedia.org/wiki/Internet_Archive)), Challenges, 17 octobre 2015_.

**Warning message:**
`[{"msg": "unrecognized time syntax in #time: '20180722200606'", "trace": "", "title": "Apple", "section": "", "subsection": "", "called_from": "parserfns/1040", "path": ["Apple", "Lien archive", "#switch", "#switch", "#ifeq", "#ifeq", "TEMPLATE_NAME", "#time", "#time"]}]`

**WikiText:**
`<ref>[http://www.challenges.fr/telecoms/20151017.CHA0608/apple-va-devoir-payer-une-grosse-amende-pour-avoir-viole-un-brevet.html Apple va devoir payer une grosse amende pour avoir violé un brevet] {{Lien archive|url=http://www.challenges.fr/telecoms/20151017.CHA0608/apple-va-devoir-payer-une-grosse-amende-pour-avoir-viole-un-brevet.html |titre=Copie archivée |horodatage archive=20180722200606 }}, ''Challenges'', 17 octobre 2015.</ref>.`

It seems to be `|horodatage archive=20180722200606` which triggers the Warning message.
This Warning appears on many pages.

**Comment by xxyzz** [comment]
This is the same error message as #211 and should be fixed by #213.

**Comment by LeMoussel** [comment]
After a `git pull` of `wikitextprocessor` and `wiktextract`, It's OK.
