### ISSUE TITLE
ERROR: unimplemented parserfn #property

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#220]
On Wikipedia [Art amarnien](https://fr.wikipedia.org/wiki/Art_amarnien) page, there is error on 
_Sur les autres projets Wikimedia :
    [Art amarnien](https://commons.wikimedia.org/wiki/Category:Amarna_art?uselang=fr), sur Wikimedia Commons_

The Wikitext template is: `{{Autres projets|commons=Category:Amarna art}}`

**Test Code:**
```python
from unittest import TestCase

from wikitextprocessor import Wtp
from wiktextract.page import clean_node
from wiktextract.wxr_context import WiktextractContext
from wiktextract.config import WiktionaryConfig


class TestProperty(TestCase):
    def setUp(self):
        self.wxr = WiktextractContext(
            wtp = Wtp(
                db_path="fr-wiki-latest.db",
                lang_code="fr",
                project="wikipedia",
            ),
            config=WiktionaryConfig()
        )

    def tearDown(self):
        self.wxr.wtp.close_db_conn()

    def test_property(self):
        self.wxr.wtp.start_page("Test property")
        tree = self.wxr.wtp.parse(text="{{Autres projets|commons=Category:Amarna art}}.", expand_all=True)
        text = clean_node(
            wxr=self.wxr,
            sense_data={},
            wikinode=tree,
        )
        self.assertGreater(len(text), 0)
```
**Output:**
```
Test property: ERROR: unimplemented parserfn #property at ['Test property', 'Autres projets', '#switch', '#switch', 'TEMPLATE_NAME', '#property', '#property']
Test property: ERROR: unimplemented parserfn #property at ['Test property', 'Autres projets', '#switch', '#switch', '#if', '#if', '#if', '#if', 'TEMPLATE_NAME', 'TEMPLATE_NAME', '#property', '#property']
```

I see that in `parserfns.py` [property ](https://github.com/tatuylonen/wikitextprocessor/blob/main/src/wikitextprocessor/parserfns.py#L1522)is not implemented.

**Comment by kristian-clausal** [comment]
`statements` has been implemented, `property` hasn't. Both of these return stuff from Wikidata, `statements` just generated images and formats stuff, while `property` is *meant* to give you raw data... But it also formats stuff. Currently, I tried to pull some wikidata coordinates, but what I got with our implementation was "Point(2.294479 48.858296)", while using Wikipedia's sandbox I got some DMS coordinates. At some point some processing is being done, which is either trivial for us (if we can pull it from Wikidata somehow) or super-annoying and probably not getting 100% done if we have to implement this stuff ourselves.

I've made a pull request that just implements property_fn by pulling the guts from statements_fn and having statements_fn call property_fn instead (because property_fn is 'raw'er, I guess...). xxyzz could take a look at it next week.

**Comment by LeMoussel** [comment]
There is a problem. After updating `wikitextprocessor` & `wiktextract`, I have the following error:
```
  File "/home/dev/Python/WikiExtractor/wikitextprocessor/src/wikitextprocessor/parserfns.py", line 1397, in property_fn
    return statement_query(wtp, prop, wikidata_item, wtp.lang_code)
  File "/home/dev/Python/WikiExtractor/wikitextprocessor/src/wikitextprocessor/wikidata.py", line 131, in statement_query
    cache_value = get_statement_cache(wtp, prop, item_id)
  File "/home/dev/Python/WikiExtractor/wikitextprocessor/src/wikitextprocessor/wikidata.py", line 79, in get_statement_cache
    for data in wtp.db_conn.execute(query, (item, prop)):
sqlite3.OperationalError: no such column: datatype
```
Indeed [property_fn](https://github.com/tatuylonen/wikitextprocessor/blob/main/src/wikitextprocessor/parserfns.py#L1384) call `statement_query`, that call [get_statement_cache](https://github.com/tatuylonen/wikitextprocessor/blob/main/src/wikitextprocessor/wikidata.py#L67)

In `get_statement_cache` we have 
```python
    query = """SELECT value, datatype FROM wikidata_property_values
    JOIN wikidata_items ON wikidata_property_values.item_id = wikidata_items.id
    JOIN wikidata_properties
      ON wikidata_property_values.property_id = wikidata_properties.id
    WHERE wikidata_items.id = ? AND """
```
but `datatype ` column doesn't exit in table `wikidata_property_values`
See [CREATE TABLE IF NOT EXISTS wikidata_property_values](https://github.com/tatuylonen/wikitextprocessor/blob/main/src/wikitextprocessor/wikidata.py#L67)

**Comment by xxyzz** [comment]
The `datatype` column was added [recently](https://github.com/tatuylonen/wikitextprocessor/commit/deceb1c99c2e0ac372de9d67a7dabe8b5b88cc7b), database created before that commit should drop the "wikidata_properties" table or delete the db file to recreate the "wikidata_properties" table.

**Comment by LeMoussel** [comment]
closed prematurely

**Comment by LeMoussel** [comment]
Anomaly resolved
