### ISSUE TITLE
ERROR: unimplemented parserfn PAGESIZE

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#223]
On Wikipedia [Cathédrale Notre-Dame de Chartres](https://fr.wikipedia.org/wiki/Cath%C3%A9drale_Notre-Dame_de_Chartres) page, there is this error:
`
Test PAGESIZE: ERROR: unimplemented parserfn PAGESIZE at ['Test PAGESIZE', 'Voir cathédrales', '#ifeq', '#ifeq', '#ifexist', '#ifexist', 'TEMPLATE_NAME', 'TEMPLATE_NAME', 'PAGESIZE', 'PAGESIZE']
Test PAGESIZE: ERROR: unimplemented parserfn PAGESIZE at ['Test PAGESIZE', 'Voir cathédrales', '#ifeq', '#ifeq', '#ifexist', '#ifexist', 'TEMPLATE_NAME', '#if', '#if', 'PAGESIZE', 'PAGESIZE']
`

The Wikitext template is: `{{Voir cathédrales|Notre-Dame|de Chartres}}`

```python
from unittest import TestCase

from wikitextprocessor import Wtp
from wiktextract.page import clean_node
from wiktextract.wxr_context import WiktextractContext
from wiktextract.config import WiktionaryConfig


class TestPagesize(TestCase):
    def setUp(self):
        self.wxr = WiktextractContext(
            wtp = Wtp(
                db_path="fr-wiki-latest.db",
                lang_code="fr",
                project="wikipedia",
            ),
            config=WiktionaryConfig()
        )


    def tearDown(self):
        self.wxr.wtp.close_db_conn()

    def test_pagesize(self):
        self.wxr.wtp.start_page("Test PAGESIZE")
        tree = self.wxr.wtp.parse(text="{{Voir cathédrales|Notre-Dame|de Chartres}}", expand_all=True)
        text = clean_node(
            wxr=self.wxr,
            sense_data={},
            wikinode=tree,
        )
        self.assertGreater(len(text), 0)
```

**Comment by LeMoussel** [comment]
There are no more errors but `text` is empty. Is this normal?

**Comment by kristian-clausal** [comment]
Yes, because {{Voir cathédrales}} doesn't create text where it is put, it creates text at the top of the article, 'outside' the main text; like a sidebar or map.

**Comment by kristian-clausal** [comment]
Actually, I'm wrong; it does create a banner if you put it later in the text other than the top. I'm looking at something right now, I'll take a look at it next week, if it's something that should be handled... The banner stuff can be considered "separate" from normal text, in which case it shouldn't be rendered here.

**Comment by kristian-clausal** [comment]
This should be fixed, please take a look.

**Comment by LeMoussel** [comment]
It's OK :ok_hand:
