### ISSUE TITLE
Template {{Voir homonymes|....}} is misinterpreted

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#225]
On Wikipedia [Aisne (département)](https://fr.wikipedia.org/wiki/Aisne_(d%C3%A9partement)) page, the wikitext of _Pour les articles homonymes, voir [Aisne](https://fr.wikipedia.org/wiki/Aisne)_ is misinterpreted.

The Wikitext template is: `{{Voir homonymes|Aisne}}`

Output Text:
`class=noviewer}
Erreur : Paramètre |texte= manquant
| texte = Pour les articles homonymes, voir Aisne.
}}`

Test code:
```python
from unittest import TestCase

from wikitextprocessor import Wtp
from wiktextract.page import clean_node
from wiktextract.wxr_context import WiktextractContext
from wiktextract.config import WiktionaryConfig


class TestHomonymes(TestCase):
    def setUp(self):
        self.wxr = WiktextractContext(
            wtp = Wtp(
                db_path="fr-wiki-latest.db",
                lang_code="fr",
                project="wikipedia",
            ),
            config=WiktionaryConfig()
        )

    def tearDown(self):
        self.wxr.wtp.close_db_conn()

    def test_homonymes(self):
        self.wxr.wtp.start_page("Test-Homonymes")
        tree = self.wxr.wtp.parse(text="{{Voir homonymes|Aisne}}", expand_all=True)
        text = clean_node(
            wxr=self.wxr,
            sense_data={},
            wikinode=tree,
        )
        self.assertGreater(len(text), 0)
```

**Comment by kristian-clausal** [comment]
I am pretty sure there's a syntax error in 

https://fr.wikipedia.org/w/index.php?title=Mod%C3%A8le:M%C3%A9ta_bandeau_de_note&action=edit

```
<includeonly>{{Méta bandeau
| forme = note
| niveau = aucun
| class = hatnote {{{class|}}}
| id = {{{id|}}}
| style = 
| icône = {{#switch: {{{icône|}}}
| confusion   = [[Fichier:Confusion colour.svg|20px|link={{{link|Aide:Homonymie}}}|alt={{{alt|Page d’aide sur l’homonymie}}}|class=noviewer]]
| homonymie   = [[Fichier:Logo disambig.svg|20px|link={{{link|Aide:Homonymie}}}|alt={{{alt|Page d’aide sur l’homonymie}}}|class=noviewer]]
| homophonie  = [[Fichier:New homoph.svg|20px|link={{{link|Aide:Homonymie}}}|alt={{{alt|Page d’aide sur l’homonymie}}}|class=noviewer]]
| paronymie   = [[Fichier:Logo disambig.svg|20px|link={{{link|Aide:Paronymie}}}|alt={{{alt|Page d’aide sur la paronymie}}}|class=noviewer]]
| redirection = [[Fichier:Arrows-move.svg|20px|link={{{link|Aide:Redirection}}}|alt={{{alt|Page d’aide sur les redirections}}}|class=noviewer]]
| redirection homophonie = [[Fichier:Arrows-move-homoph.svg|20px|link={{{link|Aide:Redirection}}}|alt={{{alt|Page d’aide sur les redirections}}}|class=noviewer]]
| stylo       = [[Fichier:Icon flat style plume 02.svg|20px|link={{{link|}}}|alt={{{alt|}}}|class=noviewer]]
| unicode     = [[Fichier:OOjs UI icon language-ltr.svg|20px|link={{{link|Aide:Unicode}}}|alt={{{alt|Page d’aide sur la police de caractères Unicode}}}|class=noviewer]]
| important   = [[Fichier:OOjs UI icon alert-destructive.svg|20px|link={{{link|}}}|alt=Important}}}|class=noviewer]]
| {{{icône|}}}
}}
| texte = {{{1|{{{texte}}}}}}
}}
```

The last case in the `switch`, `| important   = [[Fichier:OOjs UI icon alert-destructive.svg|20px|link={{{link|}}}|alt=Important}}}|class=noviewer]]` has a `}}}` triple brace that does not match inside the link. I think this should also break stuff on Wikimedia's side, but if it doesn't it means we have divergent behavior which is going to be a pain to figure out. We might be parsing triple braces too freely, maybe allowing triple braces with the wrong kind of whitespace inside (newlines, I'm thinking here)...

The usual caveat, this could turn out to be trivial, this could turn out to be a [casse-pied](https://en.wiktionary.org/wiki/pain_in_the_ass).

**Comment by LeMoussel** [comment]
I don't understand this syntax, but if I understood you correctly instead of `|link={{{link|}}}|alt=Important}}}|class=noviewer]]`, we should instead have `|link={{{link|}}}|alt={{{alt|Important}}}|class=noviewer]]`

**Comment by kristian-clausal** [comment]
Yeah, but if it's not breaking anything on Wikimedia's side better leave it be there, less an editor comes and yells at you for breaking something else. I'm trying to figure out what difference between our and theirs is.

**Comment by LeMoussel** [comment]
For information, Running `parse` & `clean_node` of 873 Wikipedia pages.

- 401 pages OK without errors
- 472 pages KO

on these KO pages

- 340 pages with this template error
- 132 pages with other errors (I will conduct an analysis to identify these other errors)

**Comment by kristian-clausal** [comment]
Yes, this would be a really common error because I get this is a pretty common template. It just found an edge case that breaks our parser, which should be possible to fix with some good luck.

**Comment by LeMoussel** [comment]
For each error, would you like me to write an issue or to write an issue in which I attach a CSV file of all the errors found per article?

**Comment by kristian-clausal** [comment]
Currently, all the errors you are bound to find might or might not be related to each other; fixing one *might* fix another, so keeping them in one big thread (for now) might be better, as a check-list. It would be nice if you could go through the errors you've found (and compiled into that list) and check whether they're relevant or not every now and then after that, as we fix issues and change things.

**Comment by LeMoussel** [comment]
OK, I create another issue as a checklist for all existing errors.

**Comment by kristian-clausal** [comment]
I think I know what the issue here is.

Normally, the extra `}}}` would cause errors in both our code and Wikimedia's parser, in the #switch statement. 

However, that triple brace `}}}` is inside a [[Fichier]]-"link". Wikimedia's parser does parsing in a different order from how we do it (no idea what, and Tatu didn't look at it either, I'm just trying to maintain what he has here), which means that the broken braces inside the Link object gets parsed as text, part of the link, instead of a brace that breaks other brace pairs outside of the link, like ours does.

```
{{#switch: 2
| 1   = [[test1|{{{NAMESPACE}}}]]
| 2   = [[test2|Important}}}]]
| 3
}}
```

This switch statement *should* work (regardless of what it picks, here it outputs a link to page `test` with the form `Important}}}`.

Links can also contain other elements, like templates and arguments, but apparently only inside the second argument. Tried it out with just `[[{{{NAMESPACE}}}]]` and that broke all parsing, returning the raw string.

A test that *should* pass for us to be correct:

```python
    def test_link7(self):
        tree = self.parse("test", "[[foo|bar}}}]]")
        link = tree.children[0]
        self.assertEqual(link.kind, NodeKind.LINK)
        self.assertEqual(link.largs, [["foo"], ["bar}}}"]])
```

Our issue is that we parse Links, Template Arguments (triple braces) and Templates inside-out with regex. The assumption is that when looping through the replacement loops (where we replace each instance of an entity like this with a magical unicode character that is later unpacked in the parser), there will be no stray braces inside the entity, because they've already be "consumed" and turned into replacement characters.

But stray braces are allowed.

Yeah, this is going to be a headache.

**Comment by LeMoussel** [comment]
There are no more errors 
But with this template `"{{Voir homonymes|Aisne}}"`,  we have the text `'class=noviewer\nPour les articles homonymes, voir Aisne.'`
Shouldn't just have `'Pour les articles homonymes, voir Aisne.'`? `class=noviewer\n` is too much?

**Comment by kristian-clausal** [comment]
Yes, I will take a look at it next week.

**Comment by kristian-clausal** [comment]
This should have been fixed now; please take a look.

**Comment by LeMoussel** [comment]
This doesn't seem OK to me.
We have this in `text`: `[Alt: Page d’aide sur l’homonymie]\nPour les articles homonymes, voir Aisne.'`
`[Alt: Page d’aide sur l’homonymie]\n` must not be present.
We also find this error in this issue https://github.com/tatuylonen/wikitextprocessor/issues/243#issuecomment-1994440201

**Comment by kristian-clausal** [comment]
That is new syntax for when we come across an image (Fichier:) and prints its alt-text. The alt text is only printed is the image is inline with the text, inside the text, and not outside of it. The syntax is meant to be easily greppable so that you can remove it in post-processing, or handle it otherwise.

**Comment by LeMoussel** [comment]
Solved with `expand_all = True` from function [parse()](https://github.com/tatuylonen/wikitextprocessor/blob/main/src/wikitextprocessor/core.py#L1913). See https://github.com/tatuylonen/wikitextprocessor/issues/243#issuecomment-2003363261

**Comment by kristian-clausal** [comment]
That doubling is a weird result, I'll take a look it tomorrow!

**Comment by kristian-clausal** [comment]
That code doesn't work. You're passing the wrong kind of handler. What is your actual code?

**Comment by LeMoussel** [comment]
sorry, I don't understand what you did. 
Can you post the code with which you performed this test?

**Comment by kristian-clausal** [comment]
Sorry, here I am asking people to post source and then I don't do it myself...


```python

from unittest import TestCase

from wikitextprocessor import Wtp
from wikitextprocessor.parser import print_tree
from wiktextract.page import clean_node
from wiktextract.wxr_context import WiktextractContext
from wiktextract.config import WiktionaryConfig

def template_handler(name, args_ht):
    if len(args_ht) > 0:
        if 'icône' in args_ht:
            del args_ht['icône']
            return None
    return None

class TestHomonymes(TestCase):
    def setUp(self):
        self.wxr = WiktextractContext(
            wtp = Wtp(
                db_path="/home/kristian/Data/htmlgen/frwp/frwp-wikt.db",
                lang_code="fr",
                project="wikipedia",
            ),
            config=WiktionaryConfig()
        )

    def tearDown(self):
        self.wxr.wtp.close_db_conn()

    
    def test_homonymes(self):
        self.wxr.wtp.start_page("Test-Homonymes")
        # https://fr.wikipedia.org/w/api.php?action=parse&text={{Voir%20homonymes|Aisne}}&contentmodel=wikitext
        tree = self.wxr.wtp.parse(text="{{Voir homonymes|Aisne}}")
        print_tree(tree)
        text = clean_node(
            wxr=self.wxr,
            sense_data={},
            wikinode=tree,
            collect_links=False,
            template_fn=template_handler,
        )    
        print(f"{text=}")
        self.assertGreater(len(text), 0)
        self.assertEqual(True, False)
```

Have you updated wikitextprocessor and wiktextract recently? Might be just mismatches with the commits/versions used.

**Comment by LeMoussel** [comment]
I made Git pull's. It's OK.

For information, here are the commits/versions used.

**wiktextract**
```bash
dev@dev-B550M-DS3H:~/Python/WikiExtractor/wiktextract$ git show
commit 2f0962f9a8b8e059df52887ff9781672b601c779 (HEAD -> master, origin/master, origin/HEAD)
Merge: 7a34845a 7381e344
Author: xxyzz <gitpull@protonmail.com>
Date:   Wed Mar 20 18:08:22 2024 +0800

    Merge pull request #554 from xxyzz/ru
    
    Add some translated tags for ru edition code
```

**wikitextprocessor**
```bash
dev@dev-B550M-DS3H:~/Python/WikiExtractor/wikitextprocessor$ git show
commit 25c097099ab9a386e8fa109af7d9f7b2691f5bff (HEAD -> main, origin/main, origin/HEAD)
Merge: 5e3e5ab 87c790c
Author: kristian-clausal <93529179+kristian-clausal@users.noreply.github.com>
Date:   Thu Mar 14 14:03:12 2024 +0200

    Merge pull request #256 from tatuylonen/formatdate
    
    Implement mw.language:formatDate()
```
