### ISSUE TITLE
zh edition dump missing many entries

### ISSUE THREAD

**Issue by garfieldnate** [tatuylonen/wikitextprocessor#23]
I noticed that extraction from the zh edition dump misses many entries; in particular, the ZH wiktionary lists [100K](https://zh.wiktionary.org/wiki/Category:%E8%8B%B1%E8%AF%AD) pages under the "English" category, but when I run extraction like so I only get 30K lines in the resulting jsonl file:

    ./wiktwords --dump-file-language-code zh --all --language en --cache /tmp/wikt-cache --pages-dir pages --out data_en_zh1.jsonl zhwiktionary-20221120-pages-articles.xml.bz2| tee log_en_zh1.txt

Some examples of missing pages are chad, acrid, acidic, zigzag, and argon; those first 4 are missing the POS headers, but [argon](https://zh.wiktionary.org/wiki/argon) has the correct structure.

I noticed that these pages all use traditional characters in the headers, which might have been a pattern, but then I noticed that "sulfate" is not missing, and it uses traditional headers.

@xxyzz

**Comment by garfieldnate** [comment]
Okay, I've downloaded the linked release and created a new list of missing words: [missing.txt](https://github.com/tatuylonen/wikitextprocessor/files/10132011/missing.txt).

I think the biggest issue here is just that the entries aren't all structured as expected. I think a huge number of pages could be extracted if the following structure were parsed (example from the `earthling` page):

    :'''earthling'''
    #[[世人]]
    #[[俗人]]
    #[[俗物]]

Other examples include paternoster, passage, brash, horoscope, insinuate, and plenty more. 

I noticed also that the Page for `Ethiopian` only contains the definition in a table of translations (with only one row...). 

The downside to parsing these pages as-is, though, would be the lack of POS information.

**Comment by xxyzz** [comment]
I take a quick look at the list, some can be parsed by adding POS or linkage subtitles to JSON files in the wiktextract data folder like "!" "'kay", "'twas". But there are also some non-existing words, like "1's complement". I not sure how wiktextract handles bad formed pages though.

Asking Chinese Wiktionary editors for help is another option. A lot of similar changes in page history are made by bots, maybe they could add POS headings by querying the same word from kaikki.org's JSON file through these bots.

An off-topic question: I wonder if [tree-sitter](https://tree-sitter.github.io) could make parsing Wiktionary more easily.

**Comment by garfieldnate** [comment]
Strange, `1's complement` is in the dump file and even has well-formed text:

    {{-n-}}
    #（電子工程）[[1補數]]

But I can't view it on zh.wiktionary.org.

Ask Wiktionary people for help is a great option, but the missing POS data is not easy to add automatically. For example, https://zh.wiktionary.org/wiki/lower. This can be an adjective or a verb (at least), and the list of Chinese translations are not separated by POS. So you would need to do some disambiguation, as well.

**Comment by xxyzz** [comment]
What's the creation data of the dump file you're using? I could find `#（電子工程）[[1補數]]` in last month's dump file zhwiktionary-20221101-pages-articles.xml.bz2.

A bot could edit pages that have only one type of POS data on English Wiktionary.

I also find the template [CC-CEDICT](https://zh.wiktionary.org/wiki/Template:CC-CEDICT) was parsed as forms, I'm looking for a place in the code to ignore this template.

**Comment by garfieldnate** [comment]
You're right, I used a download mirror that gave me a dump from September 🤦  "1's complement" is no longer an entry on Wiktionary.

>A bot could edit pages that have only one type of POS data on English Wiktionary.

I think that would be a great start.

**Comment by kristian-clausal** [comment]
I am currently studying Lua and PHP to better emulate how wikitextprocessor handles Lua. Tatu did the original implementation by looking at how wikitext works as a black box, not using the original source code exactly, so hopefully I will be able to fix a few annoying bugs, possibly including the template bug here.

I've given the error message objects in our error data a field called `called_from`; the values `core/405` and `core/427` are used for the two kinds of "heuristically added missing }" messages we have in errordata > `debug`, which might give you some information on if there's a problem with this particular issue (mismatch between our emulated wikitext and original wikitext parsers). `title` is the title of the article, ie. the word in question and `section` is the highest level section after that, language.

**Comment by xxyzz** [comment]
The "NoEdit" template doesn't make much sense to me, what it's trying to do is like this:

```
{{#if: {{{1|}}} | <div class="noedit">{{{1|}}}</div> | <span id="no-edit-0"></span>}}
```

but instead it was written as this:

```
{{#if: {{{|}}} | <div class="noedit">={{{|}}}</div> | <span id="no-edit-0"></span>}}
```

this template also hasn't been changed since 2009.

I replace the template to `{{#if: {{{1|}}} | {{{1|}}} | <span id="no-edit-0"></span>}}` then the pages use "=n=" can be parsed. I don't think it'd worth the effort to support this template. Just return the template parameter would be much easier.

**Comment by xxyzz** [comment]
I create a new release at [here](https://github.com/xxyzz/wiktextract/releases/tag/zhwiktionary-20221201). The `en-zh.json` file has 32739 lines excluding the translingual data. Changes to both projects are sent in separate pull requests. Now if a page is not included most likely is because either it lacks POS heading or it has Lua error.

**Comment by garfieldnate** [comment]
Thank you for your efforts! Since further improving the coverage requires editing Wiktionary, I would say that this issue should then be closed; but then again, I think there should be some kind of documentation to indicate the current coverage. Or maybe the wiktextract command should output the percentage of pages where a word was extracted?

**Comment by xxyzz** [comment]
The `--statistics` option prints the number of captured words and language counts. For computing the coverage would need to add some code at [here](https://github.com/tatuylonen/wiktextract/blob/330124aaa2d8c0a0f8494c3b36102de6f0966a1d/wiktwords#L423-L447).
