### ISSUE TITLE
Parasitic display "Uri:parse unexpected stuff at end:"

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#237]
Showing "Uri:parse unexpected stuff at end:" doesn't help. [mw_uri.lua -> print("Uri:parse unexpected stuff at end:", s)](https://github.com/tatuylonen/wikitextprocessor/blob/main/src/wikitextprocessor/lua/mw_uri.lua#L173)
It could be removed

**Comment by kristian-clausal** [comment]
Please add some examples so we can compare and see what is broken and what is going on. Examples are always needed.

**Comment by LeMoussel** [comment]
It's not easy to make an example. While parsing Wikipedia pages, from time to time there is the display `Uri:parse unexpected stuff at end:...`. In my humble opinion, this display does not help and pollutes the logs.
This PR removes this display just as was done in the [Uri:extend(query) function](https://github.com/tatuylonen/wikitextprocessor/blob/main/src/wikitextprocessor/lua/mw_uri.lua#L208).
