### ISSUE TITLE
Update README.md API section to mention need to iterate over Wtp.process() return value.

### ISSUE THREAD

**Issue by jcoffland** [tatuylonen/wikitextprocessor#26]
EDIT: this is a documentation issue.

I followed the instructions in the README.md and tried to run this program:

```python
from wikitextprocessor import Wtp

def page_handler(model, title, text):
  print(model, title)

ctx = Wtp(lang_code = 'fi')
ctx.process('fiwiktionary-20220101-pages-articles.xml', page_handler)
```

I get the following output:

```
  ... 10000 raw pages collected
  ... 20000 raw pages collected
  ... 30000 raw pages collected
  ... 40000 raw pages collected
  ... 50000 raw pages collected
  ... 60000 raw pages collected
  ... 70000 raw pages collected
  ... 80000 raw pages collected
  ... 90000 raw pages collected
  ... 100000 raw pages collected
  ... 110000 raw pages collected
  ... 120000 raw pages collected
  ... 130000 raw pages collected
  ... 140000 raw pages collected
  ... 150000 raw pages collected
  ... 160000 raw pages collected
  ... 170000 raw pages collected
  ... 180000 raw pages collected
  ... 190000 raw pages collected
  ... 200000 raw pages collected
  ... 210000 raw pages collected
  ... 220000 raw pages collected
  ... 230000 raw pages collected
  ... 240000 raw pages collected
  ... 250000 raw pages collected
  ... 260000 raw pages collected
  ... 270000 raw pages collected
  ... 280000 raw pages collected
  ... 290000 raw pages collected
  ... 300000 raw pages collected
  ... 310000 raw pages collected
  ... 320000 raw pages collected
  ... 330000 raw pages collected
  ... 340000 raw pages collected
  ... 350000 raw pages collected
  ... 360000 raw pages collected
  ... 370000 raw pages collected
  ... 380000 raw pages collected
  ... 390000 raw pages collected
  ... 400000 raw pages collected
  ... 410000 raw pages collected
  ... 420000 raw pages collected
  ... 430000 raw pages collected
  ... 440000 raw pages collected
  ... 450000 raw pages collected
  ... 460000 raw pages collected
  ... 470000 raw pages collected
  ... 480000 raw pages collected
Analyzing which templates should be expanded before parsing
```

Then it just ends.  No calls are made to ``page_handler()``.  What am I doing wrong?

**Comment by kristian-clausal** [comment]
Took me a while to figure out, but for Wtp.process() and Wtp.process() their doc comment lines say:

>     def process(self, path, page_handler, phase1_only=False):
>        """Parses a WikiMedia dump file ``path`` (which should point to a
>        "<project>-<date>-pages-articles.xml.bz2" file.  This calls
>        ``page_handler(model, title, page)`` for each raw page.  This
>        works in two phases - in the first phase this calls
>        ctx.collect_specials() for each page to collect raw pages,
>        especially templates and Lua modules.  Then this goes over the
>        articles a second time ("phase 2"), calling page_handler for
>        each page (this automatically calls ctx.start_page(title) for
>        each page before calling page_handler).  The page_handler will
>        be called in parallel using the multiprocessing package, and
>        thus it cannot save data in ``ctx`` or global variables.  It
>        can only return its results.  This function will return an
>        iterator that yields all the results returned by page_handler
>        (in arbirary order), except None values will be ignored.  This
>        function is not re-entrant.  NOTE: THIS FUNCTION RETURNS
>        ITERATOR AND THE RESULT MUST BE ITERATED FOR THIS TO DO
>        SOMETHING."""

So for the page_handler to actually process anything, it needs to be iterated over.

In wiktextract/wiktionary.py it's done with:

```python
    list(ctx.process(path, None, phase1_only=True))
```
so just throwing it all into a (temporary, unused) list! This is for the preprocessing step where we capture all the pages, so there's actually no page_handler callable passed into ctx.process(), but the principle holds true.

```python
import sys
from wikitextprocessor import Wtp


def page_handler(model, title, text):
    print(model, title)
    sys.stdout.flush

ctx = Wtp(lang_code = 'fi')
list(ctx.process('fiwiktionary-20230101-pages-articles.xml.bz2', 
                  page_handler))
```
printed out
```
...
wikitext Loiri
wikitext Luukkonen
wikitext Lukkari
wikitext Lukkarinen
wikitext Myyrä
wikitext Hirvi
wikitext Sikiö
wikitext Pursiainen
wikitext Hurskainen
wikitext Hurskanen
wikitext Puro
wikitext Pekonen
wikitext Savolainen
wikitext Urhonen
wikitext Lämsä
wikitext Soikkeli
wikitext Kotanen
wikitext Koponen
wikitext Pakarinen
wikitext Läylönen
wikitext Pesola
wikitext Finni
wikitext Anttila
wikitext parazit
...
```

**Comment by jcoffland** [comment]
Thank you so much.  It would be good to add the information about needing to iterate here: https://github.com/tatuylonen/wikitextprocessor#api-documentation  I was following the example and had not looked at the code docs.

**Comment by kristian-clausal** [comment]
There was an (oblique) mention in the readme about the iterator, but I added a few comments in the code example for when you want to "test" the page handler without doing a second phase, where it would normally be called.

**Comment by jcoffland** [comment]
Thanks!
