### ISSUE TITLE
Parser chokes on valid HTML attribute that looks like Wiki text

### ISSUE THREAD

**Issue by jcoffland** [tatuylonen/wikitextprocessor#27]
I ran into a problem parsing data from ``fiwiktionary-20220101-pages-articles.xml``.  Some of the expanded translation templates have ``<span>`` tags with attributes containing wiki text.

Here is a simple example of how the wikitextprocessor parser fails:

```python
#!/usr/bin/env python3

from wikitextprocessor import Wtp, WikiNode, NodeKind

text = '''
<span data-x="''test''">test</span>
'''

ctx = Wtp()
ctx.start_page('test')
print(ctx.parse(text))
```

This outputs:

```
test: DEBUG: no corresponding start tag found for </span> at ['test'] parsing 
<ROOT(['test']){} '\n<span data-x="', <ITALIC(){} 'test'>, '">test</span>\n'>
```

The input is valid but the parser thinks there's an ``ITALIC`` block in the HTML attribute and parsing of the whole ``<span>`` tag fails.

In my actual example the input text looks like this:

```xml
<span class="Zzzz linkki" data-kuvaus-param="{&quot;1&quot;: &quot;Englanti&quot;, &quot;5&quot;: &quot;|critic&lt;nowiki&gt;|&lt;/nowiki&gt;'''ise'''&quot;}" data-kuvaus="käännös/*/$2/yleinen" lang="en">[[criticise#Englanti|critic<nowiki>|</nowiki>'''ise''']]</span>
```

I'm not sure how to fix this but the parser needs to avoid looking for Wiki text inside HTML attributes.

**Comment by jcoffland** [comment]
I believe the problem starts here: https://github.com/tatuylonen/wikitextprocessor/blob/99b768b3cad5b5d98e4c49e7995c724d450d018e/wikitextprocessor/parser.py#L1449

``token_iter()`` searches for bold and italic wiki text before considering anything else.  So it will find bold or italic markers inside of an HTML tag's attributes and split the tag into multiple tokens.  Then it no longer tokenizes as valid HTML.

I believe the parser should first view the input as HTML and only then consider Wiki text inside HTML text nodes.  Would it be possible to use Python's built in HTML parsing capabilities?

**Comment by kristian-clausal** [comment]
This is a bit brute-forcey, but it doesn't break our tests (which is the most important thing, of course~).

I stole a MAGIC_ char slot and added MAGIC_SQUOTE_CHAR that I used to replace single quotes within HTML-tags (found with regex, but this isn't *parsing* per se so it should be fine), then tokenized the italics as usual and reverted the rest of the text back to using single quotes. Nothing *should* escape token_iter().

If someone has a better idea of how to do the single quote -> magic substitution, it would be appreciated. As it is, now I'm just using re.split() and then iterating over the result, checking whether the string starts and ends with < and > and string.replacing() if so.

**Comment by jcoffland** [comment]
Wow!  Thanks for the quick fix.

I think the clean way to do this would be to tokenize the input at a finer grain.  Instead of tokenizing WikiNodes directly you could first tokenize characters like ``<``, ``>``, ``/``, ``'``, etc. identifiers, i.e. tag and variable names and whitespace.  Then use recursive decent parsing on that token stream to parse WikiNodes, HTML tags and template calls.  This is a bit tricky though because the input is not guaranteed to be valid and you still want to continue the parsing in a reasonable way when you encounter bad input.  This could require backtracking.

Note, there are other problems with the current parser.  I will file another issue.
