### ISSUE TITLE
Parser fails on HTML tag spanning multiple lines

### ISSUE THREAD

**Issue by jcoffland** [tatuylonen/wikitextprocessor#28]
When parsing Wiktionary entries some of the entries, after template expansion, contain HTML tags that look like this:

```xml
<div


>
some text
</div>
```

The wikitextprocessor does not recognize the opening tag because it spans multiple lines.

**Comment by kristian-clausal** [comment]
I've fixed this with a simple one-line fix in token_iter that uses the same regex as the other weird html issue (remove newlines inside html tags), but please add some examples of these errors happening.  Even if it would be nice to handle everything correctly, if an issue is too annoying to handle or slows down the program too much, it might not be worth it to fix it.

**Comment by jcoffland** [comment]
Thanks for another quick fix.  I understand wanting to keep the code simple.  Here's an example from the expanded fiwiktionary:

From [ainutlaatuinen](https://fi.wiktionary.org/wiki/ainutlaatuinen):
```xml
...
====Lähteet====
<div id="viitteet-malline" 


>
<references> </references>
</div>
...
```

I found 17 instances of this in my subset of the fiwiktionary data.  They all come from the ``viitteet`` template and look the same.  So it's not common but it parses correctly on Wiktionary.

**Comment by kristian-clausal** [comment]
Yeah, that definitely qualifies for some fixing... I took a look at the template, and it's a Thing.

```<div id="viitteet-malline" 
{{ #ifexpr: {{ #ifeq: {{lc: {{{1|}}} }} | fontti | 1 | 0}} or {{ #ifeq: {{lc: {{{2|}}} }} | fontti | 1 | 0}} | class="references-small" }}
{{ #if: {{{sarakkeet|}}} | style="-moz-column-count:{{{sarakkeet}}}; -webkit-column-count:{{{sarakkeet}}}; column-count:{{{sarakkeet}}};" | {{ #ifexpr: {{ #ifeq: {{lc: {{{1|}}} }} | sarakkeet | 1 | 0}} or {{ #ifeq: {{lc: {{{2|}}} }} | sarakkeet | 1 | 0}} | style="-moz-column-count:2; -webkit-column-count:2; column-count:2;" }} }}
>
<includeonly>{{#tag:references|{{{viitteet|{{{refs|}}}}}} }}</includeonly>
</div><noinclude>
{{Mallineohje|Viitemallineet}}
</noinclude>```

I could change it by removing the formatting newlines, but I don't want to get into an edit spat.
