### ISSUE TITLE
`{{43e}}` not expanded

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#298]
```python
from wikitextprocessor import Wtp
from wiktextract.wxr_context import WiktextractContext
from wiktextract.config import WiktionaryConfig

wiki_config=WiktionaryConfig()
wiki_config.dump_file_lang_code = 'fr'
wiki_config.capture_language_codes = ["fr", "mul"]
wxr = WiktextractContext(
        wtp=Wtp(
            db_path="fr-wiki-latest.db",
            lang_code="fr",
            project="wikipedia",
        ),
        config=wiki_config,
)

wxr.wtp.start_page("Test page")
ret = wxr.wtp.expand("{{43e}}")
print(ret)
```

Print `[[:Modèle:43e]]`

The result should be `43e`

Ref: [Modèle:43e](https://fr.wikipedia.org/wiki/Mod%C3%A8le:43e)

**Comment by kristian-clausal** [comment]
With the same code, I am getting

```
<abbr class="abbr" title="Quarante-troisième">43<sup>e</sup></abbr>
```

on an old dump from March. The `[[:Namespace:templatename]]` seems to indicate it can't find the template in question; is this a dump from the recentish time when Wikimedia dump files were corrupted/missing files?

**Comment by LeMoussel** [comment]
OK. I will regenerate the files with a recent dump of the wikimedia database.
