### ISSUE TITLE
HTML tags in template arguments are parsed as plain text

### ISSUE THREAD

**Issue by xxyzz** [tatuylonen/wikitextprocessor#299]
Find the bug in pl edition page [Urban](https://pl.wiktionary.org/wiki/Urban)

```
: (1.1) {{odmiana-rzeczownik-polski
|Forma depr = Urbany<ref name="SGJPonline">{{SGJPonline|id=22616|hasło=Urban}}</ref>
}}
```

because this commit: https://github.com/tatuylonen/wikitextprocessor/commit/52956936298569da898d107a0432f762b3e1c123

IMO the three `or _parser_have(` lines should be removed but I don't know which part of the wiktextract code requires this behavior. All wiktextract tests pass though. Two wikitextprocessor tests added by me failed but are expected.

**Comment by kristian-clausal** [comment]
The tags are parsed as plain text because they're part of a template argument and are passed into the template as text, but is the expanded output not parsed at some point, in which case the tags would also be parsed?

**Comment by xxyzz** [comment]
If they are parsed as text then the node structs are broken and can't be used, I want to use the nodes in template arguments to find tag templates. For example:

```
: (1.1-2) {{odmiana-rzeczownik-polski
|Biernik lp = durian / {{pot}} duriana
}}
```

**Comment by kristian-clausal** [comment]
I think we need to ask Tatu about what the fix was actually for, if no tests break after removing it. It might actually be something that's been fixed some other way since 2021...

**Comment by kristian-clausal** [comment]
Tatu says:

> Some templates/modules use special markers, eg., <i>, on arguments. These are 
NOT valid HTML. I think Greek used a lot of them.
> Or maybe it was Latin.

So there are (were?) templates out there with *literal* `<i>` *text* inside of them that aren't HTML tags and should not be parsed as HTML-tags!!

**Comment by xxyzz** [comment]
Really? If they still doing that, maybe we could only parse `<i>` as plain text, and parse other tags as HTML nodes.

**Comment by kristian-clausal** [comment]
I'll take a look if I can find examples in article source pages, maybe investigate what kind of thing this is and if it's still going on.

**Comment by xxyzz** [comment]
I guess the problem was HTML nodes in template args can't be converted back to text correctly when passing args to Lua module or other templates?  But I write a test(only comment out the 3 `or` lines) and it passed:
```python
    def test_tag_in_template_arg(self):
        self.wtp.add_page(
            "Module:a",
            828,
            """
local export = {}
function export.a(frame)
  return frame:getParent().args[1];
end
return export""",
            model="Scribunto",
        )
        self.wtp.add_page(
            "Template:a",
            10,
            "{{#invoke:a|a}}",
            model="wikitext",
        )
        self.wtp.start_page("")
        self.assertEqual(
            self.wtp.expand("{{a|a<i>123}}"),
            "a<i>123",
        )
```

I also test some Latin pages with these tags like page [Noae](https://en.wiktionary.org/wiki/Noae) uses `{{la-ndecl|Noae<1.loc>}}`(declension table) and the JSON results are the same.

Maybe there are some cases I don't think of, but the code seems able to handle HTML nodes in template args. I'll process the `ref` tag plain text in wiktextract code, but I hope tags could be parsed if this doesn't require too much changes.

**Comment by xxyzz** [comment]
I resolved the issue by calling `Wtp.parse()`: https://github.com/tatuylonen/wiktextract/pull/787
