### ISSUE TITLE
HTML code in English word senses

### ISSUE THREAD

**Issue by lggruspe** [tatuylonen/wikitextprocessor#33]
Some HTML code got into the English dump.

Here's an example from [wall](https://kaikki.org/dictionary/English/meaning/w/wa/wall.html) (sense: The butterfly Lasiommata megera.)

```json
{
   "code": "sw",
   "lang": "Swahili",
   "sense": "butterfly Lasiommata megera\n class=\"translations\" role=\"presentation\" style=\"width:100%;\" data-gloss=\"butterfly Lasiommata megera\"",
   "word": "kuta"
}
```

More examples:

- [love](https://kaikki.org/dictionary/English/meaning/l/lo/love.html) (A climbing plant, Clematis vitalba)
- [rose](https://kaikki.org/dictionary/English/meaning/r/ro/rose.html)  (A plant or species in the rose family. (Rosaceae))
- [they](https://kaikki.org/dictionary/English/meaning/t/th/they.html)
- [read](https://kaikki.org/dictionary/English/meaning/r/re/read.html) (Used after a euphemism to introduce the intended, more blunt meaning of a term)

**Comment by kristian-clausal** [comment]
I've separated out the benzylidene post as its own issue, that's a different kettle of fish. The opening issue with the parsing of italics and other nodes within table attributes seems to be ok for now, so I'm closing this thread as completed.
