### ISSUE TITLE
Removing newlines from around HTML comments breaks some things

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wikitextprocessor#342]
Kaikki's been dead while I was sick due to a bunch of exceptions caused by Catalan comments on EN wiktionary:

```
==Catalan==

===Pronunciation===
* {{ca-IPA|ë}}<!-- per GDLC, DNV; not in DCVB but as a recent borrowing we would expect ë in Balearic -->
* {{audio|ca|LL-Q7026 (cat)-Unjoanqualsevol-euro.wav}}
```
The comment and newline is removed and the parser see:

```
* {{ca-IPA|ë}}* {{audio|ca|LL-Q7026 (cat)-Unjoanqualsevol-euro.wav}}
```

This messes with some silly code in /en/pronunciation.py, can be tested with euro/Catalan.

Do we need to remove newlines *before* comments? I'm not going to touch it yet in case you want to @xxyzz

**Comment by kristian-clausal** [comment]
This was actually so trivial, it fixed the issues I had with euro/Catalan, all tests pass on wikitextprocessor and wiktextract, I'm going to merge this just to get kaikki going again.

**Comment by xxyzz** [comment]
:facepalm: I should have think of this case...
