### ISSUE TITLE
Parsing typoed `={-hr-}==` has weird behavior

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wikitextprocessor#352]
Example taken from Greek Wiktionary article peta, where we have the (typoed) code

```
=={{-id-}}==

==={{ουσιαστικό|id}}===
{{τ|id|{{PAGENAME}}}}
* [[χάρτης]]

===={{συνώνυμα}}====
* [[map]]


----

={{-hr-}}==

==={{ουσιαστικό|hr}}===
{{τ|hr|{{PAGENAME}}}} {{θ}}
* [[φτέρνα]]


----

=={{-sl-}}==
...
```

EDIT: Added more context here, horizontal lines have some things going with parsing levels.

The parse tree should look similar to another header tree:

```
<LEVEL2([<TEMPLATE(['-id-']){} >]){}
   '\n\n',
   <LEVEL3([<TEMPLATE(['ουσιαστικό'], ['id']){} >]){}
      '\n', <TEMPLATE(['τ'], ['id'], [<PARSER_FN(['PAGENAME']){} >]){} > ...>>
```

but instead it looks like:

```
<LEVEL1(){}
   <TEMPLATE(['-hr-']){} >,
   '==\n\n',
   <LEVEL3([<TEMPLATE(['ουσιαστικό'], ['hr']){} >]){} 
      '\n', ...>>
```

The `{{-hr-}}` template that should be in `.largs` (like the `{{-id-}}` template for the Indonesian heading) is instead a direct child of the LEVEL1. It should be inside the parentheses, not after the `{}`. I would also expect only one `=`, but both of them are there.

Posting this as a todo for myself, it's getting late.

**Comment by xxyzz** [comment]
I have seen similar broken wikitext and I always fix them on wiktionary, they are rare. We could find these pages in the "can't find subtitle start token" debug messages.

IMO we should avoid fixing broken wikitext, even if we "fix" them the parsed nodes may still be unusable.

**Comment by kristian-clausal** [comment]
Yeah, 'fixing' these so that they're like they "should" be based on some heuristics is probably not good. BUT we can make them *fail* in the same way they fail in Wiktionary; this, plus the fact that the .largs is missing the header text is what's the problem here, the heading doesn't have a heading at all.

Trying out on the Wikipedia sandbox, we've got:

```
=control 1=   // level 1

==control 2==  // level 2

=test==  // level 1, "test="

==test2===  // level 2, "test=="

=test  // normal text "=test"

==test=  // level 1 "=test"
```

We should follow these. Currently, I think we do:

```
=test==  // level 1, empty largs , ""  //  children: "test==\n" (or children: template, "==\n" in the case in the first post)

==test2===  // level 2, empty largs // "test===" 

=test  // normal text "=test" // not parsed as header, correct

==test=  // level 2!! empty largs, // "test="
```

So they way we fail is completely different from Wikimedia.

**Comment by xxyzz** [comment]
Might be difficult to figure out all the cases and don't break correct wikitext. I'm also not sure how to implement this in wikitextprocesser code, especially for this "==test="  kinds of cases...
