### ISSUE TITLE
wikitextprocessor is not suitable to parse non-english Wikipedia

### ISSUE THREAD

**Issue by GaaH** [tatuylonen/wikitextprocessor#4]
Currently, wikitextprocessor detects template by checking if a page’s title starts with "Templates:". This strategy works with english Wikipedia, however it doesn’t with other wikis. Indeed, frwiki’s template pages start with "Modèle:", hence templates from frwiki are not properly detected.

A solution (maybe THE solution) would be to rely on the _ns_ tag in pages. For instances, pages with ns = 10 are templates pages. Another solution would be to get the prefix of namespace 10, which can be found in the _namespaces_ tag at the beginnig of an xml dump.

**Comment by tatuylonen** [comment]
Your proposed solution seems reasonable.  I'll try to implement it this week (as soon as I get inflection table parsing in wiktextract out of the way).

**Comment by GaaH** [comment]
I’m currently trying to implement something, if I achieve to make it works I’ll submit a PR.
But we need to make sure that every wiki use the key 10 to refer to namespaces. I think it is the case, but I’m not sure…

**Comment by tatuylonen** [comment]
I'll be happy to merge if you get it implemented.

**Comment by GaaH** [comment]
I did some edit to your code, you can find it on [this branch](https://github.com/GaaH/wikitextprocessor/tree/namespaces). I mostly changed how parsing a mediawiki dump is done. For instance, I switch to xml.etree to parse the xml, because the regex used to parse xml tag’s attr was not working as intended. I don’t know if it hurts speed though, but I’m sure parsing will be a lot more reliable. If you want, I can submit a PR with only the switch from regex parsing to xml.etree, without touching too much the rest of the code. If not, is there any reason not to rely on xml parsers ?

I also added some classes to represent a page, since namespace information should be part of the page attributes.

All tests are green, so I guess I did not break too much things, but I do not understand all the processes taking place in the file core.py, so I’m having troubles editing this file for now.

**Comment by tatuylonen** [comment]
I used to use one of the existing xml parsers but switched to regexps at some point.  I remember having some issues that triggered the change, but I can't now remember what exactly the issue was.  I was optimizing performance at the same time and I think the regexp approach was moderately faster.  At least would be good to compare if there is noticeable difference - though I think that there is now so much more other processing that the XML parsing speed isn't very significant.  "ns" field was listed as one of the ignored fields so if still using the regexp-based parser it would need to be removed from the ignored list.

**Comment by GaaH** [comment]
I made sure to remove "ns" from the list of ignored fields, my problem was that the tag attributes were not properly parsed by your regex. For instance, the regex retrieved only the "case" attribute in `<ns key="10" case="capitalize">Template</ns>` , while I wanted the "key".

As you say, XML parsing should not be the bottleneck here, so if you want I can compare speed of both versions and send a PR if it is indeed not slower, since this will clearly make the code more understandable.

That being said, I’m affraid parsing the dump file will not be sufficient, as I thought, to handle localized namespace names, since XML dump are laking a lot of information, such as aliases for example. Yet, this seems to be used in wikitextprocessor…
So, it seems that it would be better to hard-code configuration for each wiki, then give the proper one to the Wtp object. The real problem is (well, for me) to set programatically the right configuration to the Lua process, since hard-coding namespaces in Lua will conflict with the (hopefuly) dynamic namespaces in Python.

**Comment by xxyzz** [comment]
I'm also baffled by the hard coded namespace text in the "mw_site.lua" file. I could load namespace text from different config files for each Wiktionary dump files but don't how to do the same change to the Lua code. I'm also confused by the duplicated namespace code in the Lua code, why this is necessary since lupa already could run Python code in Lua.

**Comment by xxyzz** [comment]
I figure out how to change the namespace text in lua(https://github.com/tatuylonen/wikitextprocessor/compare/main...xxyzz:wikitextprocessor:non-eng) but I got lots of errors while running the `test_wikiprocess.py` test:

```
﻿FTt: ERROR: LUA error in #invoke ('testmod', 'testfn') parent None at ['Tt', '#invoke']
list index out of range
        Traceback (most recent call last):
        File "lupa/_lupa.pyx", line 1601, in lupa._lupa.py_object_getindex_with_gil
        File "lupa/_lupa.pyx", line 1563, in lupa._lupa.getitem_for_lua
        IndexError: list index out of range
```

```
......Tt: ERROR: LUA error in #invoke ('testmod', 'testfn') parent None at ['Tt', '#invoke']
[string "_sandbox_phase2"]:286: invalid conversion specification: '%#-d'
stack traceback:
        [C]: in global '_orig_format'
        [string "_sandbox_phase2"]:286: in function <[string "_sandbox_phase2"]:268>
        (...tail calls...)
        [C]: in function 'xpcall'
        [string "_sandbox_phase2"]:218: in function <[string "_sandbox_phase2"]:140>
```

I don't know which part of the code causes these errors, could someone take a look at my code and give some advice?

**Comment by xxyzz** [comment]
I fixed the error and only `test_string_format2` fails but this test already fails before.
