### ISSUE TITLE
Major issues with Lua memory stuff not resetting properly

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wikitextprocessor#54]
Memo to me as a reminder about these issues.

There's a major issue with the Lua engine's memory not resetting properly as it should be. Some examples:

* Before `Module:xnt-decl` was corrected on Wiktionary, it would overwrite the name `table` in global namespace, which would basically break every subsequent use of `table` (which is super-common) by the Lua engine
* The article "A 1" (because it's super early in alphabetical order, I suspect) overwrites something, like #PAGENAME or *something* similar, which causes a ton of words to have `{{head}}` templates return "A 1". This weirdness is later caught by the "suspicious unhandled suffix" error, because "A 1" looks wrong.
* There was a bug (which may or may reappear) where a/some lambda function(s) in call_lua_sandbox would "receive too many parameters"; this has to be a bug related to these memory issues, because it popped up in extract.log only about 66% of the way through the logs, which is a good indicator that there was a "trigger" function like `Module:xnt-decl` (which also showed the same behavior of errors appearing only N% through the log and which was why I was able to find the module in question), but now that I've replaced the lambdas with named functions the errors disappear for today...
* `Module:ja-translit` can't access `package` properly, for some reason, or a specific field of `package` that I don't remember right now. EDIT: probably not anything to do with this issue.

The fault is most likely somewhere in luaexec.py, _sandbox_phase1.lua or _sandbox_phase2.lua.

This may be a pre-existing issue that we didn't notice with the older versions of Lupa we were using (because there were so many issues), or it might be an issue with how we converted to using Lua 5.1, or it might be an issue with some change in Lupa or how Lupa handles Lua 5.1 stuff.

**Comment by xxyzz** [comment]
`package` is not included in the Lua sanbox's environment, but Scribunto includes some functions in that package: https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_reference_manual#Differences_from_standard_Lua

**Comment by kristian-clausal** [comment]
ja-translit was the only module to use package.loaders(), and checking out all the names mentioned there, the only module using anything from package, except for User:Qnm that doesn't seem to be used in anything. Simply adding `env["package"] = package` to the end of `_sandbox_phase1.lua` doesn't work.

**Comment by kristian-clausal** [comment]
> That's because `package.loaders[2]("Module:ja-translit/data/ja")` in MediaWiki's Lua sanbox returns `nil` but the original `loaders` function returns a error message string.

Thanks for pointing this out, it finally helped me get out of this nightmare and figure out a kludge to (apparently??) fix this. It's not pretty, but hopefully it works...

**Comment by xxyzz** [comment]
The "A 1" headword bug is caused by the old cache result in the `_sanbox_phase1.new_loadData()`: [Module:headword](https://en.wiktionary.org/wiki/Module:headword) loads [Module:headword/data](https://en.wiktionary.org/wiki/Module:headword/data) at line 10, but the [`pagename`](https://en.wiktionary.org/wiki/Module:headword/data#L-1025) variable is only updated once due to the cache, and this value is later used to assign [`default_head`](https://en.wiktionary.org/wiki/Module:headword#L-617) variable.

**Comment by kristian-clausal** [comment]
The whole kaikki regen process took about 15~16 hours this time, which is faster than before!

Also, changing the anonymous lambdas to functions with names has paid off (a bit, if it works out), there's a bunch of Lua errors triggered by something, and it seems only `debugGetParent` is affected... But grepping for GetParent in the modules doesn't find anything. The errors start to appear around 88% the way through extract.log, so they've been obviously caused by something specific triggering things, although seeing as how the errors have been absent in the couple last logs it's not as simple as the `table =` in xnt_decl. Seems to the same underlying issue of resets not working out (which is different from the cache issue xxyzz has now fixed).

**Comment by kristian-clausal** [comment]
I've tried to recreate the issue with xnt-decl by creating a composite word entry file (basically just `cat` together the files for 'skeetomp' and 'isiZulu', minus the TITLE line of one) and overriding xnt-decl with an old version with `table =` and can't recreate the issue of `table` being overwritten, even when xnt-decl is being used on the same page as other modules that access `table`.  This might indicate that the issue with globals being overwritten by other modules is resolved with xxyzz's `mw.loadData` fix; the issue with

> call_lua_sandbox.<locals>.make_frame.<locals>.debugGetParent() takes 1 positional argument but 2 were given Traceback (most recent call last): File "lupa/lua51.pyx", line 1982, in lupa.lua51.py_call_with_gil File "lupa/lua51.pyx", line 1969, in lupa.lua51.call_python TypeError: call_lua_sandbox.<locals>.make_frame.<locals>.debugGetParent() takes 1 positional argument but 2 were given - ('links/templates', 'l_term_t') 

feels like a different thing, although it also start 'expressing' in the log files after being triggered by something else.

`frame:getParent()` is the syntactic sugar used by Lua to do `frame.getParent(frame)`. At some point, a lua table/list gains a value that is being unpacked and added as a second value to `frame.getParent(frame, ???)`, which breaks our old lambda, but it seems arbitrary when this happens; the previous-previous run didn't have this happen, but the now-previous run did. It would make sense that something being unpacked would break our deanonymized debugGetParent() function (because it only gets one value, the 'self' object), but why does the unpacking trigger? Where does the extra value or whatever come from?

**Comment by xxyzz** [comment]
I searched the database to see which module page overwrites the `getParent` function:

```
sqlite> SELECT title FROM pages WHERE namespace_id = 828 AND body LIKE '%getParent = %';
+----------------------------------------+
|                 title                  |
+----------------------------------------+
| Module:ar-verb                         |
| Module:ru-noun                         |
| Module:fro-verb                        |
| Module:ar-utilities                    |
| Module:User:Benwing2/ru-noun           |
| Module:User:Erutuon/ar-verb            |
| Module:frame test                      |
| Module:User:M. I. Wright/ar test       |
| Module:User:Surjection/invoker/default |
| Module:translations/multi-nowiki       |
| Module:ko/multi                        |
| Module:documentation/translit          |
| Module:documentation/sortkey           |
| Module:documentation/entry name        |
+----------------------------------------+
```

Only [Module:ko/multi](https://en.wiktionary.org/wiki/Module:ko/multi) overwrites the function with variable number of arguments.

I also searched which page passes two arguments to `getParent`:

```
sqlite> SELECT title FROM pages WHERE namespace_id = 828 AND body 'getParent\([^)]+,[^)]+\)';
+----------------------------+
|           title            |
+----------------------------+
| Module:User:DTLHS/etymtree |
+----------------------------+
```

But [Module:User:DTLHS/etymtree](https://en.wiktionary.org/wiki/Module:User:DTLHS/etymtree) is not used in any page.

**Comment by kristian-clausal** [comment]
Yeah, and in the new upcoming kaikki regen it doesn't appear either... Ignore the "Test" prints, I forgot to remove that line when adding the debug prints into debugGetParent.

We tried to find a candidate 'poisoner' module, but most of the `getParent =` stuff doesn't seem like the culprit. They're usually returns inside a module, and don't seem to actually end up anywhere dangerous.

It is possible that the issue is fixed with the recent patches to Lua stuff, and the last time errors appeared was just something that happened because the run had started before the newest commits (and all the other related errors were suppressed by chance).

**Comment by kristian-clausal** [comment]
Confirmation that getParent() isn't the only one affected; in two separate runs yesterday (and this morning), debugGetTitle and debug_get_page_content (in different parts of Luaexec but related) get the extra arguments. I don't have the extract.log for getTitle, but the get_page_content error starts appearing around 83% the way through extract.log.

They don't have the debug prints that were added to debugGetParent, so can't tell what what page (`title`) was being processed, so I added more debug prints to catch *args.

**Comment by kristian-clausal** [comment]
Ok, in the runs I've done on the dev machine, #1 and #4 had nothing while #2 and #3 had something, and in both cases the errors are present in two functions:

> $ egrep LAMBDA extract2.log | sort | uniq -c
>     334 LAMBDA FETCH_LANGUAGE_NAME DEBUG: ('!#%%&*+/:;<=>?@[\\%]_{|}',)
>       1 LAMBDA FETCH_LANGUAGE_NAME DEBUG: ('"<>&\xa0',)
>     400 LAMBDA GETTITLE DEBUG: (title: translations): ('!#%%&*+/:;<=>?@[\\%]_{|}',)
>     141 LAMBDA GETTITLE DEBUG: (title: translations): ('"<>&\xa0',)
> $ egrep LAMBDA extract3.log | sort | uniq -c
>    1302 LAMBDA GET_PAGE_CONTENT DEBUG: ('!#%%&*+/:;<=>?@[\\%]_{|}',)
>      15 LAMBDA GET_PAGE_CONTENT DEBUG: ('"<>&\xa0',)
>     174 LAMBDA GET_PAGE_INFO DEBUG: ('!#%%&*+/:;<=>?@[\\%]_{|}',)

The ` ('"<>&\xa0',)` is from wikitextprocessor/lua/mw_text.lua:

```lua
function mw_text.encode(value, charset)
   if charset == nil then charset="\"<>& " end
   return mw_encode_python(value, charset)
end
```

`mw_encode_python` is a reference to `mw_text_encode` in luaexec.py, which is passed through `set_functions` in `call_set_functions`, where `set_functions` is `__lua_set_functions` in `_sandbox_phase2.lua`, which sets `mw_encode_python` on the Lua side so that the 'wrapper' `mw_text.encode` calls the Python function...

Then `('!#%%&*+/:;<=>?@[\\%]_{|}',)` is from Wiktionary's side in https://en.wiktionary.org/w/index.php?title=Module:string_utilities&action=edit :671

```lua
-- Convert risky characters to HTML entities, which minimizes interference once returned (e.g. for "sms:a", "<!-- -->" etc.).
function export.escape_risky_characters(text)
	if text:match("\"'") then
		for _, pattern in ipairs(require("Module:languages/data/patterns")) do
			text = text:gsub(pattern, function(m1) return mw.text.encode(m1, "\"'") end)
		end
	end
	-- Spacing characters in isolation generally need to be escaped in order to be properly processed by the MediaWiki software.
	if not mw.ustring.match(text, "%S") then
		return mw.text.encode(text, "%s")
	else
		return mw.text.encode(text, "!#%%&*+/:;<=>?@[\\%]_{|}")
	end
end
```

So in both cases, `mw.text.encode` points to the wrong function for some reason.

`mw` has a custom `__index` function (if I understand correctly, the basic function called for foo[bar] and probably foo.bar 
and foo:bar at some point) in mw.lua:

```lua
local mw_autoload = {
   hash = "mw_hash",
   html = "mw_html",
   language = "mw_language",
   site = "mw_site",
   text = "mw_text",
   title = "mw_title",
   uri = "mw_uri",
   ustring = "ustring:ustring",
   wikibase = "mw_wikibase",
   getContentLanguage = function(table)
      return table.language.getContentLanguage
   end,
   getLanguage = function(table)
      return table.language.getContentLanguage
   end
}

local mw_meta = {}

-- This is intentionally a global variable, as this is accessed by many modules
mw = {
   -- addWarning  (see below)
   -- ... removed comments
   -- ustring - autoloaded
}
setmetatable(mw, mw_meta)

function mw_meta.__index(table, key)
   local modname = mw_autoload[key]
   if modname == nil then return nil end
   local ret
   if type(modname) == "string" then
      ret = require(modname)
   elseif type(modname) == "function" then
      ret = modname(table)
   else
      error("mw_meta.__index had modname", modname)
   end
   table[key] = ret
   return ret
end
```

**Comment by xxyzz** [comment]
Does this error also occurs with a single process(`--num-threads 1`)? Just to make sure it's not related to the forked memory.

**Comment by kristian-clausal** [comment]
> Does this error also occurs with a single process(`--num-threads 1`)? Just to make sure it's not a concurrency bug.

The bug is hard to replicate (it comes and goes), so we'd have to wait to catch it. I'm going to quickly check how long a full reprocessing would take with --num-threads 1.

**Comment by kristian-clausal** [comment]
Currently with num-threads=1, the estimate is 3600 hours. From experience I know this number will drop quite dramatically, but it will still be probably several days or a few weeks to run. I really hope it's not a multiprocessing bug, (and it shouldn't be, because all of this is happening in separate processes that shouldn't have shared memory)...

**Comment by xxyzz** [comment]
Do you think add [`traceback.print_stack()`](https://docs.python.org/3/library/traceback.html#traceback.print_stack) inside `call_set_functions.debug_get_page_content()`'s `if` block or  use [pdb](https://docs.python.org/3/library/pdb.html) would help?

```python
def call_set_functions(ctx, set_functions):
    def debug_get_page_info(x, *args):
        if args:
           import traceback
           logging.debug(f"LAMBDA GET_PAGE_INFO DEBUG: {repr(args)}, {ctx.title=}")
           traceback.print_stack()
        return get_page_info(ctx, x)
```

```python
def call_set_functions(ctx, set_functions):
    def debug_get_page_info(x, *args):
        if args:
           import pdb
           logging.debug(f"LAMBDA GET_PAGE_INFO DEBUG: {repr(args)}, {ctx.title=}")
           pdb.set_trace()
        return get_page_info(ctx, x)
```

**Comment by kristian-clausal** [comment]
I'll add those prints and traceback before I go home for the weekend and leave a loop of runs for the weekend.

**Comment by kristian-clausal** [comment]
From extract log of run 5 (the rest didn't happen over the weekend because of a crash):

```
    503 LAMBDA GETTITLE DEBUG: (title: IPA/templates): ('!#%%&*+/:;<=>?@[\\%]_{|}',)
    224 LAMBDA GETTITLE DEBUG: (title: IPA/templates): ('#%%&+/:<=>@[\\%]_{|}',)
   2646 LAMBDA GETTITLE DEBUG: (title: IPA/templates): (':',)
     49 LAMBDA GETTITLE DEBUG: (title: IPA/templates): ('"<>&\xa0',)
```
The usual suspect, mw.text.encode; the one with 224 occurences was from Module:links

**Comment by kristian-clausal** [comment]
There are already errors in log #6, and they've got the python-side stack trace prints:

```
...
    ret = invoke_fn(args, expander, parent)
  File "/home/kristian/Projects/lambdaloop/temp-wiktionary/wikitextprocessor/wikitextproces
sor/core.py", line 999, in invoke_fn
    ret = call_lua_sandbox(self, invoke_args, expander, parent, timeout)
  File "/home/kristian/Projects/lambdaloop/temp-wiktionary/wikitextprocessor/wikitextproces
sor/luaexec.py", line 608, in call_lua_sandbox
    ret = ctx.lua_invoke(modname, modfn, frame, ctx.title, timeout)
  File "/home/kristian/Projects/lambdaloop/temp-wiktionary/wikitextprocessor/wikitextproces
sor/luaexec.py", line 255, in debug_fetch_language_name
    traceback.print_stack()
```

Unfortunately, there's not much there. The errors all seem to come through mw.text.encode, as usual.

**Comment by kristian-clausal** [comment]
As an update, xxyzz has committed some code that isolates Lua invocations better, which should, at the very least, cause this bug to have less of an impact if or when it happens. Tatu, who has a background in C, is now working on trying to figure out what the underlying cause is, but he says it might never be found by us (if it exists on the C-code level, which he believes it does because it's so weird).

Currently, xxyzz's commit seems to have eliminated certain log messages we use for debugging this (ie. the error doesn't happen), after about 20-24 test runs, so things look extremely promising.

**Comment by kristian-clausal** [comment]
The lua invocation isolation patches from xxyzz seem to have done their job, because I haven't seen any triggers of debug messages since then! Closing this for now.
