### ISSUE TITLE
Detecting whether a page contains an entry for a specific language

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wikitextprocessor#56]
Reminder to me. Not a high priority, but could be nice for testing and for people who only work with specific languages.

Now that there is a database, it would be helpful if we could add some meta-data for each page that is added to it, before the page is parsed in a costly way. There are some things that should be possible to detect with simple string-searches and patterns, the trouble is just being exhaustive and correct.

Detecting whether a page contains a section for a specific language should not be impossible. At first glance it would just be a search for headers that contain the language name or a variant of that name.

The page id and language id could then be added as a new record into a new table that contains these combinations ('chat' id -> 'English' id; 'chat' id -> 'French' id, etc.), and using that table we can filter what pages to use in when processing specific languages.

The stuff with the table records is pretty simple, but the detection of language is the kind of thing that can be annoying. Are there any edge cases where the simple `look for '$=*(Language|Name|Variations)` isn't enough?

**Comment by xxyzz** [comment]
Probably don't need a new table if the query only have to run once with query like this: `SELECT * FROM pages WHERE body LIKE '%==English==%';`.

And some Wiktionary uses templates for language headers, for example: https://zh.wiktionary.org/wiki/Template:Zh. So the query will be `SELECT * FROM pages WHERE body LIKE '%=={{zh}}==%';`

**Comment by kristian-clausal** [comment]
> Probably don't need a new table if the query only have to run once with query like this: `SELECT * FROM pages WHERE body LIKE '%==English==%';`.

How costly are the options? The records needed for page -> language A, page -> language B doesn't seem super-huge (I bet it's on average a really low number per page, 2 or maybe 3 different languages in your average Wiktionary page), and you could do it just once upfront when creating the database.

Conversely, doing what amounts to big grep operations on each page is less costly than actually parsing the whole page, but is "LIKE" meant to be used with large pieces of text? The examples I've seen mostly involve small strings (but I haven't looked into it too deeply yet).

> And some Wiktionary uses templates for language headers, for example: https://zh.wiktionary.org/wiki/Template:Zh. So the query will be `SELECT * FROM pages WHERE body LIKE '%=={{zh}}==%';`

I bet there's even more ways people do this... `{{zh}}` isn't too bad yet, but you'd still need to create a separate list.

**Comment by xxyzz** [comment]
The simple `LIKE` query take a few seconds, more complex query would takes longer. [`FTS5`](https://www.sqlite.org/fts5.html) can be used for searching large collection of documents but it's take some time to index.

The profile results shows the `call_lua_sandbox()` takes the most of the execute time, following by `get_page()` and `re.sub()` , profile command: `py-spy top -s -r 1 -- wiktextract/wiktextract/wiktwords.py --all --all-languages --out data.json --db-path sqlite_db enwiktionary-20230520-pages-articles.xml.bz2`

The bottleneck is at the lua sandbox not the parser, I guess the current language filter is fine.

**Comment by kristian-clausal** [comment]
Closed; this isn't actually a wikitextprocessor issue, should be moved to wiktextract, but there isn't much to say. Using SQL LIKE should be enough.
