### ISSUE TITLE
Template regex in `Wtp._encode()` can't match templates that has `-{}-` argument

### ISSUE THREAD

**Issue by xxyzz** [tatuylonen/wikitextprocessor#59]
Chinese Wiktionary template [Ja-romanization of](https://zh.wiktionary.org/wiki/Template:Ja-romanization_of) uses `-{}-` as a placeholder for the first unnamed argument of module [form of/templates](https://zh.wiktionary.org/wiki/Module:Form_of/templates), `-{}-` will be replaced to empty string by MediaWiki. But the template regex at here https://github.com/tatuylonen/wikitextprocessor/blob/04cec9ff80094c91c8174b7dab125629399c081c/wikitextprocessor/core.py#L563-L572

can't match the `#invoke` function and the whole invoke function got expanded as plain text.

`ja-romanization of` template wikitext: `{{#invoke:form of/templates|form_of_t|-{}-|withcap=1|lang=ja|noprimaryentrycat=}} 的[[罗马字]]转写`

I tried to replace `-{}-` with a white space before calling `_encode` but I guess some Lua code removes the empty string argument and throws a "parameter 1 is required" error.  Maybe a more complex regex could solve this bug.

Example of affected page: https://zh.wiktionary.org/wiki/manga#日語

**Comment by kristian-clausal** [comment]
We could steal a MAGIC character slot, replace `-{}-` with it, and then return it as needed.

In common we have:
https://github.com/tatuylonen/wikitextprocessor/blob/04cec9ff80094c91c8174b7dab125629399c081c/wikitextprocessor/common.py#LL8C1-L18C1

The magic characters and the range are just unused Unicode characters that should be safe to sprinkle into strings.

Here we could add a MAGIC_ZH_PLACEHOLDER by shifting MAGIC_FIRST to 0x0x00102040 and giving 0x0010203f to MAGIC_ZH_PLACEHOLDER, cast it as a character in MAGIC_ZH_PLACEHOLDER_CH and do string replacements back and forth between the magic character and `-{}-` as needed.

(Note to self: replace magic values with MAGIC_BASE_VALUE + N.)

This is what I did when I needed to somehow fix an issue with quote single quote `'` apostrophes inside double-quoted HTML attributes when parsing.
